Include airports and airspaces in topview
Open-MSS/MSS pull request #1089
Opened 2021-07-20 11:22 UTC by Marilyth

Allows the visualisation of airports and airspaces through the topview.
Airports will automatically be downloaded, airspaces require a manual download.

2021-07-22 11:08 UTC, ReimarBauer requested changes
not finished with review.

2021-07-22 11:08 UTC, ReimarBauer commented on mslib/msui/mpl_map.py
> +                self.crs_text.set_text("Airspaces provided by openaip.net\n" + self.crs_text.get_text())
theire suggestion is:

Airspaces Data used comes from openAIP. Visit openAIP.net and contribute to better aviation data, free for everyone to use and share.

2021-07-22 12:11 UTC, Marilyth commented on mslib/msui/mpl_map.py
> +                self.crs_text.set_text("Airspaces provided by openaip.net\n" + self.crs_text.get_text())
Updated

2021-07-27 06:44 UTC, ReimarBauer reviewed
in the mss ui About we should add a section for displaying NOTICE (rendered) or some new menu.

in the index.py we could add a menu which shows NOTICE (rendered) too

2021-07-27 13:23 UTC, joernu76 commented
Nothing serious, but I got this RuntimeError message when pressing the "this directory" button:
```
INFO: Launching user interface...
Initializing caja-open-terminal extension
Initializing caja-image-converter extension
RuntimeError: object at 0x7fede458b540 of type RenameMenu is not initialized
```
The correct directory *does* open, though.

2021-07-27 13:28 UTC, joernu76 commented
I also guess, the airports should be plotted *above* the airspaces. Currently, they are hidden.

2021-07-27 13:29 UTC, joernu76 commented
Last, I suggest to move the functionality to a dockwidget. I feel that we need to add some more filters/functions to this feature, which would be a bit much for this option diaglogue...?

2021-07-27 13:29 UTC, joernu76 commented
Pretty nifty, overall!

2021-07-28 08:30 UTC, Marilyth commented
@joernu76 
Airspaces now don't need a manual download anymore, so the RuntimeError should be gone?
Airports are rendered above airspaces.
Functionality has been moved to a dockwidget.

2021-08-01 11:12 UTC, ReimarBauer reviewed
I would prefer a progress bar for the Update/Download feature. I do see currently info entries on the terminal.

2021-08-01 11:17 UTC, ReimarBauer commented
the selection dropdown may get a select all / unselect all feature.

2021-08-01 12:08 UTC, ReimarBauer approved these changes
Thx, that is a big step further.

2021-08-02 10:57 UTC, merged