Clean up utils into own submodules
Open-MSS/MSS pull request #1168
Opened 2021-08-23 10:11 UTC by Marilyth

Fixes #1131 
Cleans up most of utils.py and groups the functions/classes into other submodules
mslib/utils/airdata.py
mslib/utils/config.py
mslib/utils/coordinate.py
mslib/utils/time.py
mslib/msui/mss_qt.py

2021-08-23 13:32 UTC, ReimarBauer requested changes
Much changes :) 


can you please split the tests.py module too. we should have a test_ module for any (new) module in utils.

2021-08-23 13:37 UTC, ReimarBauer commented
I'm not happy with the module name "time". But I have also no better idea.

2021-08-24 08:18 UTC, Marilyth commented
The tests belonging to a specific utils module have been moved to their own files

2021-08-25 14:09 UTC, Marilyth commented
I should not have done that before the GSOC merge, oh god.

2021-08-26 18:06 UTC, ReimarBauer requested changes
please see comment in test_config.py

2021-08-26 18:06 UTC, ReimarBauer commented on mslib/utils/_tests/test_config.py
> +<<<<<<< HEAD
have a look on this merge conflict

2021-08-27 09:21 UTC, ReimarBauer approved these changes
Thx

2021-08-27 09:21 UTC, merged