merging in GSOC2021-AravindMurali
Open-MSS/MSS pull request #1171
Opened 2021-08-23 13:20 UTC by joernu76

Result of `git merge --squash`

Squashed commit of the following:

commit c4b273c32bf750e5590e761369ef110f355f6cb5
Merge: e6014c04 d7716ba0
Author: ReimarBauer <rb.proj@gmail.com>
Date:   Mon Aug 23 15:10:26 2021 +0200

    Merge pull request #1169 from aravindm711/gsoc-develop-merge-4

    Gsoc develop merge 4

commit d7716ba0db286944b8f8a9a12d5954bc73dbc331
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Mon Aug 23 17:11:00 2021 +0530

    refactored tests for help dialog

commit 111f64cfd858b9d051ed4278185bea03c2a15e07
Merge: e6014c04 da77f881
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Mon Aug 23 16:58:35 2021 +0530

    Merge branch 'develop' into gsoc-develop-merge-4

    # Conflicts:
    #	mslib/mscolab/_tests/test_chat_manager.py
    #	mslib/mscolab/_tests/test_file_manager.py
    #	mslib/mscolab/_tests/test_files.py
    #	mslib/mscolab/_tests/test_files_api.py
    #	mslib/mscolab/_tests/test_seed.py
    #	mslib/mscolab/_tests/test_server.py
    #	mslib/mscolab/_tests/test_user.py
    #	mslib/mscolab/_tests/test_utils.py
    #	mslib/msui/_tests/test_mscolab.py

commit e6014c0431730e4749af5d856c53aff32340bbc9
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Sun Aug 22 11:49:12 2021 +0530

    GSoC update - Updated MSColab help dialog (#1161)

    * partially updated mscolab help dialog

    * updated mscolab help dialog

    * updated collaborator description

commit b6517e2c53cd57ef64d2c125cae9f2e80ad16258
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Sun Aug 22 02:46:33 2021 +0530

    GSoC config editor update 3 - refactor of config_loader (#1159)

    * refactor of config_loader

    * moved config class to config submodule

    * moved config related tests to its own submodule; extended test scope

    * fixed restart bug

commit 7a104646b42d5971eb21196ea37bcbe3c97a3f7b
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Wed Aug 18 01:04:20 2021 +0530

    GSoC config editor update 2 - validations (#1154)

    * added validations for config options

    * removed comments; fixed bugs

    * changed shortcut for views to meta for macOS

    * changed dialogs from question to warning

commit 3cf5476d907c6f6f818b26d2634e02968de5ee66
Merge: 242f1f99 478af6b7
Author: ReimarBauer <rb.proj@gmail.com>
Date:   Wed Aug 11 15:14:21 2021 +0200

    Merge pull request #1143 from aravindm711/GSOC2021-AravindMurali_gets_updated

    GSoC develop merge 3

commit 478af6b7556990c9a9d4528a331d17c6e87f8f60
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Wed Aug 11 17:37:40 2021 +0530

    added assert statements from recent changes in develop

commit bec4268c6cc4debddd5a923230174e70f56753ea
Merge: 242f1f99 36f4467b
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Wed Aug 11 17:22:26 2021 +0530

    Merge branch 'develop' into GSOC2021-AravindMurali_gets_updated

    # Conflicts:
    #	mslib/msui/_tests/test_mscolab_version_history.py

commit 242f1f990461064ae58474d4e24df7c3c0b89ce3
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Wed Aug 11 13:09:20 2021 +0530

    GSOC Config editor update (#1103)

    * initial implementation of profile window; extended test scope

    * completed profile window implementation and related tests

    * fixed flake8 test failure

    * fixed http auth bugs; extended test scope

    * added qt-json-view to support dir; added info in NOTICE

    * modified qt-json-view; mentioned modifications in readme

    * tested qt-json-view for proper usability

    * Provide same test signature

    * fixed failing test

    * handled socket conn exception; cleaned up unwanted comments

    * started implementation of config editor window

    * partially implemented merging user settings with default; fixed tests

    * implemented merging of default and user settings

    * implemented remove option handler

    * fixed bugs in 'remove' functionality

    * implemented restore defaults functionality

    * fixed restore default bugs and added logging statements

    * implemented import, export, save_restart

    * added comments

    * moved import/save/export options to toolbar

    Co-authored-by: May <baermay98@gmail.com>

commit ff38534156c4d540dff4480f8c09cc5400381f05
Merge: f57bbb8c ae254f06
Author: J. Ungermann <j.ungermann@fz-juelich.de>
Date:   Wed Aug 4 10:46:43 2021 +0200

    Merge pull request #1119 from aravindm711/gsoc-develop-merge-2

    Gsoc develop merge 2

commit ae254f0636b7f25c44cc44273b1246de3f03acb0
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Tue Aug 3 14:04:24 2021 +0530

    changed connect_window in tests to non modal to prevent time-out

commit 9dad7624e8b3ecc25a182b1f9a219a9fc0c6fe8b
Merge: f57bbb8c 7d4d924a
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Tue Aug 3 10:12:47 2021 +0530

    Merge remote-tracking branch 'upstream/develop' into gsoc-develop-merge-2

commit f57bbb8cff1536a0098558abab3c1c6ebe825899
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Fri Jul 23 16:22:12 2021 +0530

    New Profile window (#1086)

    * initial implementation of profile window; extended test scope

    * completed profile window implementation and related tests

    * fixed flake8 test failure

    * fixed http auth bugs; extended test scope

    * Provide same test signature

    * fixed failing test

    Co-authored-by: May <baermay98@gmail.com>

commit 853e2d581f73a000989659b1053507fdaa5b49db
Merge: 69672e4e 7050cd9d
Author: ReimarBauer <rb.proj@gmail.com>
Date:   Sun Jul 18 07:29:12 2021 +0200

    Merge pull request #1082 from aravindm711/gsoc-develop-merge

    Gsoc develop merge

commit 7050cd9d263e2141b963e6899dc716d4459035af
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Sat Jul 17 16:08:16 2021 +0530

    fixed tests; merged open/import

commit 8c0f78846ba7849eddd85c6b4a7d73a56ae82657
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Thu Jul 15 14:24:31 2021 +0530

    fixed mainwindow tests

commit 69672e4e0699e410aec634ed59c055ec732fc297
Merge: 018babe0 45b23432
Author: ReimarBauer <rb.proj@gmail.com>
Date:   Thu Jul 15 09:45:19 2021 +0200

    Merge pull request #1079 from aravindm711/GSOC2021-AravindMurali

    GSoC Progress Update 2 - Integrated plugins, refactored tests

commit 19faae626fd3ff96a3b75ed47e45119edee26e89
Merge: 45b23432 e2607fb8
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Tue Jul 13 20:11:23 2021 +0530

    Merge remote-tracking branch 'upstream/develop' into gsoc-develop-merge

    # Conflicts:
    #	mslib/msui/_tests/test_mscolab.py
    #	mslib/msui/_tests/test_mss_pyui.py
    #	mslib/msui/mscolab.py

commit 45b23432f87a52c85e69217911daf7fefc15ccc4
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Tue Jul 13 19:51:05 2021 +0530

    fixed requested changes

commit d8d79871f8645ecfedacef3a484e9c4bfebd1966
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Tue Jul 13 10:55:53 2021 +0530

    fixed failing tests and flake8 errors

commit 38107a772647abd8e1bc46fdaa8006eba7613199
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Sun Jul 11 15:47:38 2021 +0530

    added plugin filter to add project browse; refactored tests

commit 018babe00170ffa737c730fd0d61f37978115166
Merge: 7895db82 4eecd757
Author: J. Ungermann <j.ungermann@fz-juelich.de>
Date:   Thu Jul 8 09:05:37 2021 +0200

    Merge pull request #1059 from aravindm711/GSOC2021-AravindMurali

    GSoC progress update

commit 4eecd7575e1882486a821680409b84b271058cb1
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Wed Jul 7 15:03:13 2021 +0530

    integrated plugins with save flighttrack

commit a4fdf64a8d17e5faaaf9182c01b2b6a9e5241ac3
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Mon Jul 5 21:23:04 2021 +0530

    removed activate flighttrack submenu

commit 1f723613e39d41495b4838351443d407a54c8466
Author: Aravind Murali <aravindmurali711@gmail.com>
Date:   Fri Jul 2 16:27:33 2021 +0530

    made some imp [...]

2021-08-23 14:34 UTC, ReimarBauer requested changes
needs an update, setting on hold ;)

2021-08-24 06:17 UTC, joernu76 commented
updated.

2021-08-24 11:37 UTC, ReimarBauer approved these changes
Thx

2021-08-24 12:03 UTC, aravindm711 approved these changes

2021-08-24 12:33 UTC, merged