changes on UI and models for using categories
Open-MSS/MSS pull request #1191
Opened 2021-09-05 11:04 UTC by ReimarBauer

2021-09-05 11:05 UTC, ReimarBauer commented
I look next on filing a default on project creation from the mss_settings.json

2021-09-06 07:50 UTC, joernu76 requested changes

2021-09-06 07:50 UTC, joernu76 commented on mslib/msui/mscolab.py
> -            self.add_proj_dialog.description.textChanged.connect(check_and_enable_project_accept)
This should not have been removed.?

2021-09-06 15:22 UTC, ReimarBauer commented on mslib/msui/mscolab.py
> -            self.add_proj_dialog.description.textChanged.connect(check_and_enable_project_accept)
good catch :)

2021-09-07 05:24 UTC, joernu76 commented on mslib/msui/mscolab.py
> +            self.add_proj_dialog.description.textChanged.connect(check_and_enable_project)
"_accept" is missing

2021-09-07 07:34 UTC, joernu76 approved these changes

2021-09-07 07:34 UTC, merged