Show Operation Description Below Connected URL
Open-MSS/MSS pull request #1284
Opened 2021-10-18 16:17 UTC by Jatin2020-24

Fixes: #1281 
Fixes: #1286

2021-10-20 17:46 UTC, ReimarBauer commented on mslib/msui/qt5/ui_mainwindow.py
> +
I guess this is created by the -x flag of pyuic5?
We don't need this extra code to test and display the class.

2021-10-21 03:03 UTC, Jatin2020-24 commented on mslib/msui/qt5/ui_mainwindow.py
> +
Removed extra code.

2021-10-21 06:23 UTC, ReimarBauer approved these changes
see a question in the comment.

I have looked on the last used descriptions of the CIRRUS campaign. All used fits to the line.
We can change this when someone has a usecase for much more words.

2021-10-21 06:23 UTC, ReimarBauer commented on mslib/msui/qt5/ui_mainwindow.py
> +        self.activeOperationDesc.setText(_translate("MSSMainWindow", "Select Operation to View Description."))
@Jatin2020-24 I tried to find where this text is shown. When and where is it?

2021-10-21 09:06 UTC, Jatin2020-24 commented on mslib/msui/qt5/ui_mainwindow.py
> +        self.activeOperationDesc.setText(_translate("MSSMainWindow", "Select Operation to View Description."))
if we add command `self.ui.activeOperationDesc.setHidden(False)` in `after_login` function then this text will be visible.
It will be good idea to show this text immediately after login, so user can easily understand how to see operation description.
![InkedScreenshot (318)_LI](https://user-images.githubusercontent.com/72596619/138241049-00a32887-5600-4ddf-80d9-acdddaad6770.jpg)

2021-10-21 17:04 UTC, ReimarBauer requested changes
a small change as suggested :)

2021-10-21 17:04 UTC, ReimarBauer commented on mslib/msui/qt5/ui_mainwindow.py
> +        self.activeOperationDesc.setText(_translate("MSSMainWindow", "Select Operation to View Description."))
that's a good idea, please do so.

2021-10-21 17:08 UTC, ReimarBauer commented
found another problem.

with logout the description must be cleared. Currently after the next login without selection the old text is shown again

2021-10-22 15:30 UTC, Jatin2020-24 commented
now long descriptions (more than 95 chars) can be viewed from operations menu and for short desc. (less than 95 chars) can be viewed either from MSColab main window or in operation menu.
Tooltip has also been extended by "double-click" line.
![new](https://user-images.githubusercontent.com/72596619/138481341-2e380980-308d-47f2-9715-4901ffb75650.gif)

2021-10-25 12:48 UTC, ReimarBauer reviewed
We have to take care on users which are stressed and so I think we should write 

Double click a operation to activate and view its description.

That is usually what a user won't know, how to get it activated.

Then it is "viewing description" an addon to the tooltip which is given from "Flight Tracks"

2021-10-25 12:52 UTC, ReimarBauer commented
Somehow I have the same problem as you showed in the gif too, it does not react on my first "ok" click. Also a click on the corner "x" does not destroy it on first attempt. 

interestingly sometimes it works perfect.

2021-10-25 13:51 UTC, ReimarBauer requested changes
see comments.

if the closing of the window did not work as expected (many times of ok clicking) and there is no solution yet please add a # ToDo review closing of widget to that definition.

2021-10-25 13:51 UTC, ReimarBauer commented on mslib/msui/mscolab.py
> +            self.error_dialog = QtWidgets.QErrorMessage()
in this case it is no "error" likly information, or description.

please have a look if we can use too:
QtWidgets.QMessageBox.information

2021-10-27 04:24 UTC, Jatin2020-24 commented on mslib/msui/mscolab.py
> +            self.error_dialog = QtWidgets.QErrorMessage()
changed error diaog to QMessage.information.

But, it is also not closing on single click.

2021-10-27 11:34 UTC, ReimarBauer commented on mslib/msui/mscolab.py
> +            self.error_dialog = QtWidgets.QErrorMessage()
I created another issue to review this. It can be also closing and immeaditly reopen again.
But that is independent from this feature.

2021-10-27 11:36 UTC, ReimarBauer approved these changes
Thx

2021-10-27 11:36 UTC, merged