Fix mamba installation
Open-MSS/MSS pull request #1298
Opened 2021-11-27 08:56 UTC by sr1j

Fixes mamba failing to install MSS. 

While installing MSS, the following error appears:
```
Encountered problems while solving.
Problem: nothing provides basemap 1.0.7 needed by mss-1.2.1-py27_0
```
This occurs because Mamba keeps python 3.10 unless explicitly mentioned, and currently we don't have a python 3.10 release.
Related: #613

2021-11-27 10:18 UTC, ReimarBauer commented
> Fixes mamba failing to install MSS.
> 
> While installing MSS, the following error appears:
> 
> ```
> Encountered problems while solving.
> Problem: nothing provides basemap 1.0.7 needed by mss-1.2.1-py27_0
> ```
> 
> This occurs because Mamba keeps python 3.10 unless explicitly mentioned, and currently we don't have a python 3.10 release. Related: #613

not exactly but close ;)

someone implemented to use float comarison instead of version string comparison. It searches for python 3.1 not "3.10"

2021-11-27 10:22 UTC, ReimarBauer requested changes
please send a PR to stable.  but bugreport first, we like to document before.

I will later merge stable to development.

2021-11-27 10:22 UTC, ReimarBauer commented on README.md
> +    $ conda create -n mssenv python=3.9
please remove =3.9

seems there are more occurencies of this problem interpreting a version string as float number ;)

adding the python modul will release automatically the fixation and we will not need to adjust when we can use 3.10 agaon

2021-11-27 10:22 UTC, ReimarBauer commented on README.md
> +    $ conda install mamba
this depends but will not cause trouble if you are using mambaforge

2021-11-27 10:55 UTC, ReimarBauer commented on README.md
> +    $ conda create -n mssenv python=3.9
and if conda "create -n mssenv mamba python" works we should do that

2021-11-30 18:46 UTC, sr1j commented
Hi @ReimarBauer , 
I tried removing =3.9 and I also tried `conda create -n mssenv mamba python`, and neither of them worked.
When I ran the following, I didn't get any errors related to Python 3.1:
```
conda create -n mssenv python
conda activate mssenv
conda install mamba
```

Can you tell me which conda version are you using? Mine is 4.11.0. I think the error depends on the conda version.
I  found out a bug on conda: https://github.com/conda/conda/issues/10969, which could be responsibe for the error, but I didn't get that error.

I also wanted to ask: Isn't it good to specify the Python version while creating the conda environment? Related: https://github.com/mamba-org/mamba/issues/1245.

I'll open the bug report issue and open the new PR once we come to a conclusion on the issue here. Is that alright?
Thank you! : )

2021-12-02 16:33 UTC, ReimarBauer commented
We should always start with an issue before fixing something. Because all discussions are now hidden in the PR after it is merged/closed and it is quite difficult to reread or search for this.

When an issue gets added I could have labled it by 6.0.1 so it is clear that we want the fix in stable.

We link issues in the releases so everyone can find the PR.

2021-12-02 16:44 UTC, ReimarBauer commented
I do also have the recent version and I tried the instructions from
https://mss.readthedocs.io/en/stable/installation.html#install

The version string is added on build time of the documentation. May be this can be done by an variable similiar in the README?
```
$ conda create -n mssenv mamba
$ conda activate mssenv
(mssenv) $ mamba install mss=6.0.0 python
(mssenv) $ mss
```

2021-12-02 16:57 UTC, ReimarBauer commented
We do build MSS for many python versions https://anaconda.org/conda-forge/mss/files

The fixation of the (most recent) python version is currently not mandatory for using MSS. Updating packages to a newer python version sometimes eats time. There can be an OS user which can't use a specified version of python because of some dependencies are not solved. 

We came to the solution  to force the version of MSS and let the system solve based on the fixations in the meta.yaml what the user can get.

2021-12-06 06:20 UTC, sr1j commented
>We should always start with an issue before fixing something. Because all discussions are now hidden in the PR after it is merged/closed and it is quite difficult to reread or search for this.
When an issue gets added I could have labled it by 6.0.1 so it is clear that we want the fix in stable.
We link issues in the releases so everyone can find the PR.
A first issue could have been just the description of the problem. The PR afterwards brings the solution ;)

Ah, got it. Thank you for explaining.
I've opened an issue and a PR for the same. Pls review it.

2021-12-06 06:45 UTC, closed without merging