do not run tests twice
Open-MSS/MSS pull request #1340
Opened 2022-01-31 09:04 UTC by joernu76

2022-01-31 12:04 UTC, joernu76 commented
@ReimarBauer Do you have an idea, why this does not work? On data-retrieval, this (seems to?) works as expected...

2022-01-31 16:23 UTC, ReimarBauer requested changes
use one list item per line.

2022-01-31 16:23 UTC, ReimarBauer commented on .github/workflows/python-flake8.yml
> +    - develop, stable
from the yaml tutorial this should as list one item per line 
or you need brackets, e.g.  branches: [ develop, stable ]

see 
- https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

(I guess it searches now the whole string of the line)

2022-01-31 16:23 UTC, ReimarBauer commented on .github/workflows/testing.yml
> +    - develop, stable
same "develop, stable" may not work

2022-02-01 06:23 UTC, ReimarBauer approved these changes
thx

2022-02-01 06:23 UTC, merged