converted all f-strings to % for logging an mentioned in issue #1205
Open-MSS/MSS pull request #1425
Opened 2022-04-17 14:58 UTC by DipanshuShukla

converted all f-strings to % for logging an mentioned in issue #1205

2022-04-18 08:15 UTC, DipanshuShukla commented
why did these tests fail?

2022-04-18 15:48 UTC, ReimarBauer commented
Have a look on the "Details" for flake8
https://github.com/Open-MSS/MSS/runs/6059325533?check_suite_focus=true
The other two I Iook at.

2022-04-18 17:14 UTC, ReimarBauer requested changes
Have a look on the oldstyle syntax and check also erros of tests

2022-04-18 17:14 UTC, ReimarBauer commented on mslib/mscolab/file_manager.py
> +                logging.debug("malicious request: %s" % user)
the "," should be correct here

2022-04-18 17:16 UTC, ReimarBauer commented
> why did these tests fail?

the dockerimage was not correct, fixed that. But tests have errors, please check

2022-04-19 05:38 UTC, ReimarBauer commented
@DipanshuShukla please have a look on https://docs.python.org/3/howto/logging.html#logging-variable-data

2022-06-08 07:21 UTC, ReimarBauer commented
we can reopen it when continuing

2022-06-08 07:21 UTC, closed without merging