replaced f' strings with % for logging
Open-MSS/MSS pull request #1426
Opened 2022-04-19 03:22 UTC by Ritwikrajsingh

2022-04-19 07:06 UTC, ReimarBauer commented
You could run the tests locally, see https://mss.readthedocs.io/en/stable/development.html?highlight=pytest#run-tests

2022-04-25 09:44 UTC, joernu76 commented on mslib/mswms/mswms.py
> +    updater.on_update_available.connect(lambda old, new: logging.info("MSS can be updated from %s to %s.\nRun"
There are several issues with PEP8 compliance here (see failed pipeline).
Here, you need to either align the second string with the line before or join the two strings in a new line (more options are likely possible).
Use pycodestyle or flake8 to test locally. We use some specific configurations to reduce the nagginess of the tools, depending on how you call them, you might get slightly different results than the pipeline. See setup.cfg.

2022-04-25 14:38 UTC, ReimarBauer requested changes
Hi, there is also a flake 8 failure in 

mslib/mscolab/mscolab.py:144:128: E501 line too long (134 > 127 characters)
1     E501 line too long (134 > 127 characters)
1     E999 IndentationError: unindent does not match any outer indentation level

2022-04-25 14:38 UTC, ReimarBauer commented on mslib/mswms/wms.py
> +	def __init__(self):
This looks like an indenting problem. 

In python a tab is 8 blanks. Indenting for one level is 4 blanks.

Which IDE do you use?

2022-04-25 15:11 UTC, ReimarBauer commented on mslib/mswms/wms.py
> +	def __init__(self):
This is a good tutorial for using flake8
https://siderlabs.com/blog/automatically-review-code-for-python-projects-using-flake8-6fcb056a001a/

2022-04-26 02:33 UTC, Ritwikrajsingh commented on mslib/mswms/wms.py
> +	def __init__(self):
I use vscode

2022-04-26 07:58 UTC, ReimarBauer commented on mslib/mswms/wms.py
> +	def __init__(self):
You may want to configure it to use python indenting style, see https://peps.python.org/pep-0008/#indentation

I assume there is a config option to use python indenting.  @joernu76 have you a picture where that needs to become configured.

https://github.com/Open-MSS/MSS/runs/6159304098?check_suite_focus=true#step:6:1123

2022-06-08 07:21 UTC, ReimarBauer commented
we can reopen it when continuing

2022-06-08 07:21 UTC, closed without merging