Adding leave operation option in properties menu
Open-MSS/MSS pull request #1438
Opened 2022-05-01 08:26 UTC by sr1j

Fixes #1322

2022-05-01 14:15 UTC, ReimarBauer requested changes
see comments

2022-05-01 14:15 UTC, ReimarBauer commented on mslib/mscolab/file_manager.py
> +        if self.is_admin(user.id, op_id) and user.id in u_ids:
our current tests only cover the else condition. You could create a local coverage by
``` pytest --cov-report html --cov mslib ```
this stores in MSS/htmlcov the report.

add a decriptive comment to the conditions for which case they are needed.  A test which covers the lines helps us not to remove/refactor this, because than the test will break,

We should make sure that a user can only remove himself as none admin from the OP and not use "/delete_bulk_permissions" to remove users from any other OP. 
Besides is_admin we also have is_collaborator. Perhaps a "is_member" can be created which covers all accesslevels or also a "is_viewer" . A test which shows that it is safe would be pretty good.

in the else part we should verify that the user is in that OP ;)

![file_mananger](https://user-images.githubusercontent.com/278728/166148337-9513a067-b852-47a1-9871-dec74b983cf9.png)


not self.is_admin(user.id, op_id)

2022-05-04 10:05 UTC, ReimarBauer requested changes
a few little things to improve, mostly done.

see also on our chat.

2022-05-04 10:05 UTC, ReimarBauer commented on mslib/mscolab/file_manager.py
> +        permi = Permission.query.filter_by(u_id=u_id, op_id=op_id).first()
please keep the word "perm" someone else has used in the other methods.

2022-05-04 10:05 UTC, ReimarBauer commented on mslib/mscolab/file_manager.py
> +        if not permi:
better compare please to None

if perm is not None:

 we abuse boolean here and some other none cpython interpreter can do it wrong

2022-05-04 10:05 UTC, ReimarBauer commented on mslib/mscolab/file_manager.py
> +        if not perm:
if perm is not None:

2022-05-04 10:05 UTC, ReimarBauer commented on mslib/mscolab/file_manager.py
> +        permi = Permission.query.filter_by(u_id=u_id, op_id=op_id).first()
please use  perm = 

so that someone reading this on some place will know Permission is meant

2022-05-05 21:06 UTC, ReimarBauer requested changes
I double checked the differnces between creator and admin role.

creator is only the user who created the operation. This one can delete the operation. 
The user has automatically the admin role which allows to add other users.
There can be more users with admin role. A user with the admin role should be able to remove himself too.

please have a look on this too. The test was missing before you started already.

```
--- a/mslib/mscolab/_tests/test_file_manager.py
+++ b/mslib/mscolab/_tests/test_file_manager.py
@@ -68,6 +68,8 @@ class Test_FileManager(TestCase):
         self.vieweruser = get_user('UV30@uv30')
         assert add_user('UV40@uv40', 'UV40', 'uv40')
         self.collaboratoruser = get_user('UV40@uv40')
+        assert add_user('UV80@uv80', 'UV80', 'uv80')
+        self.adminuser = get_user('UV80@uv80')
         assert add_user('UV50@uv50', 'UV50', 'uv50')
         self.op2user = get_user('UV50@uv50')
         assert add_user('UV60@uv60', 'UV60', 'uv60')
@@ -79,6 +81,60 @@ class Test_FileManager(TestCase):
     def tearDown(self):
         pass
```
```
    def test_admins_when_not_creator_should_be_able_to_remove_themselves(self):
        # creator is the one who creates the operation
        # a creator can't be removed from an operation and can't change this. 
        # Only creator role gives the option to delete the operation
        # admin is a role to add users.
        # the creator has also this role. But there could be more admins
        # A user with the admin role should be able to remove himself
        with self.app.test_client():
            flight_path, operation = self._create_operation(flight_path="saturn")
            assert operation.path == flight_path
            self.fm.add_bulk_permission(operation.id, self.user, [self.adminuser.id], "admin")
            assert self.fm.is_admin(self.adminuser.id, operation.id) is True
            assert self.fm.delete_bulk_permission(operation.id, self.user, [self.user.id]) is False
            assert self.fm.delete_bulk_permission(operation.id, self.user, [self.adminuser.id]) is True
            assert self.fm.delete_bulk_permission(operation.id, self.adminuser, [self.adminuser.id]) is True
            assert self.fm.delete_bulk_permission(operation.id, self.adminuser, [self.user.id]) is False
            ```

2022-05-10 02:31 UTC, sr1j commented
Moin @ReimarBauer, thank you for explaining the difference between creator and admin. I've updated the tests, please take a look : ).

2022-05-10 17:58 UTC, ReimarBauer commented on mslib/mscolab/_tests/test_file_manager.py
> +            # user (admin of operation1) has no right leave operation1
in this case self.user was the creator and therefore has no right to leave operation1 It is only the comment which is not exact. This one at same time has also admin role ;)

You can leave it like this because then it is consistent with the next lines. Or if you like change it.

2022-05-10 18:02 UTC, ReimarBauer submitted a review, later dismissed
great :)

2022-05-11 02:04 UTC, sr1j commented
Hi @ReimarBauer , I just realised that i've some more things to fix.

2022-05-11 03:03 UTC, sr1j commented on mslib/mscolab/_tests/test_file_manager.py
> +            # user (admin of operation1) has no right leave operation1
I've fixed it : )

2022-05-11 03:13 UTC, sr1j commented
Moin @ReimarBauer, I've added one more change. Please check.

2022-05-11 08:17 UTC, ReimarBauer requested changes
Found by using the ui a difference to the past. Please have a look on the gifsycle. Please have a look if this easy solvalble.

2022-05-11 08:17 UTC, ReimarBauer commented on mslib/mscolab/_tests/test_file_manager.py
> +            # The change is so that vieweruser (any user other than admin) can leave the operation
just seen that, 

any user other than **creator**)

2022-05-11 08:17 UTC, ReimarBauer commented on mslib/mscolab/_tests/test_file_manager.py
> -            result = (False, None, 'Not an admin of this operation')
This should be possible for the admin role too. This squence shows what the meaning is. This is an important feature because when we have several users on a server we can copy all roles and users from one operation to an other. 
The feature is similar to manual add members for the admin role. creator and admin role should be able to use it.

![admin_should_be_able_to_import](https://user-images.githubusercontent.com/278728/167797656-e3571124-8807-43a1-9753-655e65ab8909.gif)

2022-05-12 05:02 UTC, sr1j commented on mslib/mscolab/_tests/test_file_manager.py
> -            result = (False, None, 'Not an admin of this operation')
Ah, got it. I've fixed it : ).

2022-05-12 12:36 UTC, ReimarBauer approved these changes
Thx

2022-05-12 12:36 UTC, merged