Draft for making styles configurable.
Open-MSS/MSS pull request #1514
Opened 2022-08-08 09:07 UTC by joernu76

Fix #1509

2022-08-08 09:08 UTC, joernu76 commented
@crolf Moin, Can you have a look at the ice cloud styles? I do not understand the use of dataname. In case a "different" dataname is used the program will crash because clev was not set. Is this intended?

2022-08-08 10:19 UTC, crolf commented
Moin moin @joernu76, yes that's true. And of course it is not intended to crash the program ;-) The plotting classes where only intended to use for the ice_cloud products. I wanted to avoid to create too many styles. But maybe it would be better to create one plot style for each of the three parameter:
- ice_cloud_number
- ice_cloud_iwc
- ice_cloud_radius
and not to use the dataname if statements.
What do you think ?

2022-08-08 10:55 UTC, joernu76 commented
> Moin moin @joernu76, yes that's true. And of course it is not intended to crash the program ;-) The plotting classes where only intended to use for the ice_cloud products. I wanted to avoid to create too many styles. But maybe it would be better to create one plot style for each of the three parameter:
> 
>     * ice_cloud_number
> 
>     * ice_cloud_iwc
> 
>     * ice_cloud_radius
>       and not to use the dataname if statements.
>       What do you think ?

Agree. The intent of this change is to move the definition of new styles *from* MSS core code *to* mswms_settings.py files such that the list does not grow too large.

I'll prepare a draft.

2022-08-09 13:13 UTC, crolf approved these changes, later dismissed
Looks good to me! It is a much cleaner solution than before.

2022-08-09 16:52 UTC, joernu76 commented
@ReimarBauer Why isn't Christian's review sufficient?

2022-08-09 17:24 UTC, ReimarBauer submitted a review, later dismissed
We should document in one of the functions or in the docs the meaning of the parameters and theire type.

2022-08-09 17:24 UTC, ReimarBauer commented on mslib/mswms/utils.py
> +def _style_default(_dataname, _style, cmin, cmax, cmap, _data):
_data and _style is not used in the functions?

2022-08-09 17:24 UTC, ReimarBauer commented on mslib/mswms/utils.py
> +        cmin, cmax = 0, 1
cmin, cmax are here integers

2022-08-09 17:24 UTC, ReimarBauer commented on mslib/mswms/utils.py
> +        cmin = 0.
here it is a float

2022-08-09 17:24 UTC, ReimarBauer commented on mslib/mswms/utils.py
> +    colors = [
hmm. some don't have the hemisphere as _hemisphere placeholder

2022-08-09 17:24 UTC, ReimarBauer commented on mslib/mswms/utils.py
> +            _styles[style](dataname, style, cmin, cmax, cmap, data)
ok, here are always 6 arguments passed and there are few by a name convention which have 7, which get translated

2022-08-09 17:24 UTC, ReimarBauer commented on mslib/mswms/utils.py
>      if clev[0] == clev[-1]:
min len of clev is 2

2022-08-09 21:08 UTC, ReimarBauer commented
> Why isn't Christian's review sufficient?

github destinguishs between contributor and first time contributor.

crolf has not done yet a MR. 

On the first MR of a new user also one of us have to enable the tests 

Christian has done code commits on our old home on bitbucket with a different name, https://www.openhub.net/p/mss/contributors?query=christian&time_span=&sort=commits

2022-08-10 11:40 UTC, ReimarBauer requested changes
missing int/float in utils

2022-08-10 11:40 UTC, ReimarBauer commented on mslib/mswms/utils.py
>          cmin, cmax = 0, 1
Here is another INT definition

2022-08-10 11:44 UTC, ReimarBauer approved these changes
Thx

2022-08-11 05:47 UTC, merged