draft
Open-MSS/MSS pull request #1524
Opened 2022-08-11 12:42 UTC by joernu76

2022-08-12 07:12 UTC, joernu76 commented
@jgrooss @crolf @gisi90 It would be nice if you could comment on this as you are "the target group". Is the refactoring/documentation useful for getting started in generating your own plotting layers?
For more involved plots I expect people to study the code, but something "simple" should be quickly conjured up.

As next step I would migrate some of the defined plots (and our own additions) to a plugin/sample directory.

2022-08-12 07:55 UTC, jgrooss commented
I don't get the point how to use the new generic plot style. Is there already a plugin directory with samples?

2022-08-12 09:17 UTC, joernu76 commented
> I don't get the point how to use the new generic plot style. Is there already a plugin directory with samples?

It is not new, I just try to document it. This implies that this sample for plotting CH3Br is unclear?
```
    import mslib.mswms.generics as generics
    generics.register_standard_name(
        "mole_fraction_of_CH3Br",
        "pmol/mol"
    )
    # ...
    import mslib.mswms.mpl_hsec_styles
    register_horizontal_layers = [
        (mslib.mswms.mpl_hsec_styles.HS_GenericStyle_PL_mole_fraction_of_CH3Br, ["mydata"])]
```

Apparently I am to brief in my explanation. I see that I should certainly add how the "standard" classes are named. Can you be more specific what your problems are? Not understanding it is a bit too unspecific.

2022-08-12 09:57 UTC, ReimarBauer commented on mslib/mswms/generics.py
> +    :copyright: Copyright 2016 Joern Ungermann
2022, if that is a new module

2022-08-12 10:40 UTC, crolf commented
> @jgrooss @crolf @gisi90 It would be nice if you could comment on this as you are "the target group". Is the refactoring/documentation useful for getting started in generating your own plotting layers? For more involved plots I expect people to study the code, but something "simple" should be quickly conjured up.
> 
> As next step I would migrate some of the defined plots (and our own additions) to a plugin/sample directory.
> 
> UPDATE: In the documentation, the relevant new section is the one called "Additional plotting layers". The remainder are only syntactically changes.

For me the documentation is clear. But maybe you could add one sentence to the "Generic plotting layers" part that hints how to create the generic name "HS_GenericStyle_PL_mole_fraction_of_CH3Br". Something like "Generic style class  + level + variable e.g. 'HS_GenericStyle'+ '_PL' + '_mole_fraction_of_CH3Br'. If you never used generic classes that could be helpful.

2022-08-12 10:48 UTC, crolf commented
Nice! Now, it should really clear.

2022-08-12 11:18 UTC, jgrooss commented
Thanks. The description in `mswms.rst`, sounds logical to me now. I personally still need to understand the structure of plot classes. Therefore sample files like `mswms_plotting_layer.py.sample` are extremly valuable.

2022-08-12 11:41 UTC, joernu76 commented
> Thanks. The description in `mswms.rst`, sounds logical to me now. I personally still need to understand the structure of plot classes. Therefore sample files like `mswms_plotting_layer.py.sample` are extremly valuable.

Agreed. I thought we had _something_ but we didn't, so I set out to have a starting point. 

But I think that any more complex work requires a deeper understanding of the MSWMS component that requires looking at the code. However, where to draw the line I am not sure. 

Next steps would be more samples/plugins.

2022-08-16 10:11 UTC, gisi90 commented
I just read through the updated documentation. I guess in summary there are 5 ways for plots (so far I am only familiar with 1 and 2, and was not aware of 4 and 5):
1 use the default plots in mpl_hsec_styles/mpl_vsec_styles
2 add own styles directly to mpl_hsec_styles/mpl_vsec_styles (cf. L14 in mswms.rst)
3 create own styles in extra files (e.g. samples mss_chem_plots.py, mswms_plotting_layer.sample; mss_chem_plots.py is referred to in the standalone setup but not in the custom plotting layers section)
4 use generics style with default settings (generics.register_standard_name in wms config file)
5 use generics style with modification (use make_generic_class in mpl_hsec_styles/mpl_vsec_styles; examples are included)

Haven't tried 4/5 by myself but documentation for usage looks ok to me as well. In HS_Generic_Style one maybe should add that its not just chemical mixing rations but also "other stuff" like in VS? ("comment #filled contour plot of cloud cover" in generic VS L62 is a bit confusing).

2022-08-22 07:33 UTC, ReimarBauer requested changes
Please add a comment into

https://github.com/Open-MSS/MSS/blob/develop/mslib/mswms/demodata.py#L1001

e.g.

```
# for defining new visualisation styles, we provide ducumentation an examples on
# https://mss.rtfd.io/en/stable/mswms.html#mswms-wms-a-ogc-web-map-server
#
```

Then the link to the documentation is in the mswms_settings.py each one can create for demodata

2022-08-22 09:12 UTC, ReimarBauer requested changes
see comments

2022-08-22 09:12 UTC, ReimarBauer commented on docs/mswms.rst
> +All data files belonging to one "set" shall have a common string in its name
I stumble here every time. set has guaranteed a defined meaning in python for the unambiguousness.

Maybe pattern fits better here. in principle, we describe the assignment by a pattern. And this gives then the collection ...

My feeling is collection fits better and we should describe the pattern matching. As a result we have a set ;)

2022-08-22 09:12 UTC, ReimarBauer commented on docs/mswms.rst
> +units are 'dimensionless', 'hPa', 'm**2', 'm.s^-1', 'millibar', 'knots',
likly the `**` need an escaping

2022-08-22 09:12 UTC, ReimarBauer commented on docs/mswms.rst
> +from the mslib.mswms.mss_hsec_styles and mslib.mswms.mss_vsec_styles modules
ToDo: We could think on a refactoring (renaming) of the styles
e.g. from mslib.mswms.styles import hsec, vsec, lsec
(ok for now)

2022-08-22 09:12 UTC, ReimarBauer commented on docs/mswms.rst
>  At current state we have to use pip to install mod_wsgi into the INSTANCE environment::
oh, I think this is outdated, because we have a build on conda-forge 
https://anaconda.org/conda-forge/mod_wsgi
ToDo Reimar: review and update

2022-08-22 09:12 UTC, ReimarBauer commented on mslib/mswms/mpl_hsec_styles.py
> +        name = f"{standard_name}_{vert}"
please add a docstring, what is the meaning of fnord?

2022-08-22 09:12 UTC, ReimarBauer commented on mslib/mswms/mpl_vsec_styles.py
> -        dataname = entity
please add a docctring to the class fnord

2022-08-22 18:56 UTC, ReimarBauer approved these changes
Thx

2022-08-25 12:12 UTC, merged