Better restrict longitudes to map range for cylindric projections
Open-MSS/MSS pull request #1568
Opened 2022-09-27 15:24 UTC by joernu76

Fix #1565

2022-09-27 17:06 UTC, ReimarBauer requested changes
have a look on my comment about the decorator `@` syntax and also the image comparison.

2022-09-27 17:06 UTC, ReimarBauer commented on mslib/msui/remotesensing_dockwidget.py
> +    @ staticmethod
this extra blank sounds wrong. I would have expected a syntax error, which didn't occure, however there is no example with a blank in.

https://book.pythontips.com/en/latest/decorators.html

2022-09-27 17:06 UTC, ReimarBauer commented on mslib/msui/remotesensing_dockwidget.py
> +        lins = list(zip(lon_lin[0: -1], lon_lin[1:], lat_lin[0: -1], lat_lin[1:]))
Definitly better readable, this unbalanced whitespace around the colon got me to look into 
https://realpython.com/python-pep8/
For extended slices it is different.

2022-09-27 17:13 UTC, ReimarBauer commented
I'm not familar with this so I have no idea, if this lower left  "red circle" is expected or there should be only a parallel line?

![ex2](https://user-images.githubusercontent.com/278728/192592210-33f254cc-8152-4ec7-b3f1-20bcd5b5105f.png)

2022-09-28 06:53 UTC, joernu76 commented on mslib/msui/remotesensing_dockwidget.py
> +        lins = list(zip(lon_lin[0: -1], lon_lin[1:], lat_lin[0: -1], lat_lin[1:]))
That was autopep8 from my Visual Studio Code. I am not certain whether to agree, but I thought that autopep8 probably overrules my taste?
As there were only few changes to the file, I did not revert them.

2022-09-28 07:01 UTC, joernu76 commented
The style changes were introduced by my autopep8 in VS Code during a syntactically incorrect file save and not reverted after fixing the error. Stupid, useless tool. I thought there were fine, but you convinced me of the opposite.

2022-09-28 07:02 UTC, joernu76 commented
The first image, how did you produce that? Both cylindric and stereographic should look very smilar. And they do on my end...

2022-09-28 07:13 UTC, ReimarBauer commented
I get this always by

![example](https://user-images.githubusercontent.com/278728/192712788-1ff094a0-85ca-4a7f-847e-3109cc242955.gif)

2022-09-28 07:28 UTC, ReimarBauer commented
> The style changes were introduced by my autopep8 in VS Code during a syntactically incorrect file save and not reverted after fixing the error. Stupid, useless tool. I thought there were fine, but you convinced me of the opposite.

They could have used the common autopep8 from pypi, but I am also not using this. So no idea if it is better.

2022-09-28 07:31 UTC, joernu76 commented
> > The style changes were introduced by my autopep8 in VS Code during a syntactically incorrect file save and not reverted after fixing the error. Stupid, useless tool. I thought there were fine, but you convinced me of the opposite.
> 
> They could have used the common autopep8 from pypi, but I am also not using this. So no idea if it is better.

That's what they use. When there is a syntactically wrong string or class definition, autopep8 sometimes screws over the formatting. When the error is fixed, it only reverts part of the stuff. :-(

2022-09-28 07:31 UTC, joernu76 commented
> I get this always by
> 
> ![example](https://user-images.githubusercontent.com/278728/192712788-1ff094a0-85ca-4a7f-847e-3109cc242955.gif) [ ![example](https://user-images.githubusercontent.com/278728/192712788-1ff094a0-85ca-4a7f-847e-3109cc242955.gif) ](https://user-images.githubusercontent.com/278728/192712788-1ff094a0-85ca-4a7f-847e-3109cc242955.gif) [ ](https://user-images.githubusercontent.com/278728/192712788-1ff094a0-85ca-4a7f-847e-3109cc242955.gif)

got it!

2022-09-28 14:14 UTC, ReimarBauer approved these changes
Thx

2022-09-28 14:14 UTC, merged