updated our version string definition
Open-MSS/MSS pull request #1663
Opened 2023-02-04 20:47 UTC by rootxrishabh

fixes #1660 

setuptools now requires the __version__ variable to NOT end with a '.'

2023-02-04 21:09 UTC, ReimarBauer commented
The test ist now broken too, for what it should test, because the rule had changed. The test needs now to become more clever, see test_milestone_url(self):
I gives no failuren, because it finds now 7.0, which exists.
There should be another check, e.g. endswith(..) 

Please verify that this points to the right version. I assume that needs changes too.
https://github.com/Open-MSS/MSS/blob/stable/mslib/msui/msui.py#L331

2023-02-04 21:10 UTC, ReimarBauer requested changes
see comments

2023-02-05 17:48 UTC, rootxrishabh commented
I have made some suggestions regarding the test, as for this [link] (https://github.com/Open-MSS/MSS/issues?q=is%3Aclosed+milestone%3A{__version__[:-1]}). I found the result, attached as a screenshot.
![image](https://user-images.githubusercontent.com/73490663/216836185-78ef6bab-9412-43ff-adcc-1ff14eb0aa15.png)

2023-02-05 17:50 UTC, rootxrishabh commented
Also, I didn't find "self.milestone_url" anywhere other than the link which you attached.

2023-02-06 14:17 UTC, ReimarBauer commented
No but the "version" var you change if I search for that this is on many places used.  E.g. it is also responsible for creating the docs, for installing the right version.



e.g. 

![version_string](https://user-images.githubusercontent.com/278728/216991333-4d72bb58-a5cd-442b-9deb-0cc67da10a51.png)

improve the test in a way that it can't go wrong 

instead of the test code you can do that manually:


```
>>> import sys
>>> from mslib.msui import msui
>>> from PyQt5 import QtWidgets, QtTest
>>> application = QtWidgets.QApplication(sys.argv)
>>> window = msui.MSUI_AboutDialog()
>>> window.milestone_url
'https://github.com/Open-MSS/MSS/issues?q=is%3Aclosed+milestone%3A7.0.7'
```
The pattern matching is wrong for the current release, when you remove the 7, it gets 7.0
https://github.com/Open-MSS/MSS/blob/stable/mslib/msui/_tests/test_msui.py#L47

think about to get a good check for a version string, which is not a float number.

2023-02-09 16:20 UTC, rootxrishabh commented
I'll work on finding one

2023-02-10 13:14 UTC, ReimarBauer commented
this is one of the many descriptions of pytest around

https://realpython.com/pytest-python-testing/

2023-02-26 15:43 UTC, rootxrishabh commented
@ReimarBauer I have added the test please check.

2023-02-26 20:55 UTC, ReimarBauer requested changes
when I search for "version[" by pycharm, I guess any other IDE has also search capabilities, there is another python script which needs a fix.

2023-02-26 20:55 UTC, ReimarBauer commented on mslib/_tests/test_version.py
> +import pytest
have a look on our template https://github.com/Open-MSS/MSS/blob/develop/new_file_template.py
and use the header.

2023-02-26 21:06 UTC, ReimarBauer commented
remove also the version pinning of setuptools as I entered as workaround.
https://github.com/Open-MSS/MSS/commit/db1fd0ae792212af494cc6ea33b296a52f7674cc

2023-02-27 20:45 UTC, rootxrishabh commented
@ReimarBauer fixing linters errors in this seem complicated, can you help?

2023-02-27 20:47 UTC, rootxrishabh commented
> remove also the version pinning of setuptools as I entered as workaround. [db1fd0a](https://github.com/Open-MSS/MSS/commit/db1fd0ae792212af494cc6ea33b296a52f7674cc)

Do you mean to add back the "." here?
https://github.com/Open-MSS/MSS/pull/1663/files#diff-76811c9b5f89d75f6c9f60f28c5347ba58baa0c8f42854a7b01d2b8648c27758

2023-02-28 12:51 UTC, ReimarBauer commented
> 



> > remove also the version pinning of setuptools as I entered as workaround. [db1fd0a](https://github.com/Open-MSS/MSS/commit/db1fd0ae792212af494cc6ea33b296a52f7674cc)
> 
> Do you mean to add back the "." here? https://github.com/Open-MSS/MSS/pull/1663/files#diff-76811c9b5f89d75f6c9f60f28c5347ba58baa0c8f42854a7b01d2b8648c27758

No, definitily not, the fix is to get the last dot removed. 

I mean you can search in pycharm and find where  the changes in slicing a string gets now wrong, when there is one character less than before.

2023-02-28 12:53 UTC, ReimarBauer commented
btw. you could also run the linter test locally. It describes where the error is and how it should be fixed.

mslib/_tests/test_version.py:34:1: E302 expected 2 blank lines, found 1
1     E302 expected 2 blank lines, found 1

If you want to run the linter test locally, you can take the line from
https://github.com/Open-MSS/MSS/blob/develop/.github/workflows/python-flake8.yml#L30

2023-02-28 13:03 UTC, ReimarBauer commented
The previous version of your new test was working, this version shows this failure
https://github.com/Open-MSS/MSS/actions/runs/4286831053/jobs/7466924218#step:9:668

2023-03-01 09:03 UTC, rootxrishabh commented
> > 
> 
> > > remove also the version pinning of setuptools as I entered as workaround. [db1fd0a](https://github.com/Open-MSS/MSS/commit/db1fd0ae792212af494cc6ea33b296a52f7674cc)
> > 
> > 
> > Do you mean to add back the "." here? https://github.com/Open-MSS/MSS/pull/1663/files#diff-76811c9b5f89d75f6c9f60f28c5347ba58baa0c8f42854a7b01d2b8648c27758
> 
> No, definitily not, the fix is to get the last dot removed.
> 
> I mean you can search in pycharm and find where the changes in slicing a string gets now wrong, when there is one character less than before.
> 
> the meaning of version pinning is, that there is used a "specific" version of some module. I changed the module versions in the docker container by adding setuptools. My workaround was to use older versions of setuptools, You can see what I did, when you look at the commit, I showed. [db1fd0a](https://github.com/Open-MSS/MSS/commit/db1fd0ae792212af494cc6ea33b296a52f7674cc)

Yes, I saw that you used a specific version of setuptools to make a workaround, I found this file "MSS-stable\docs\conf.py" with incorrect version slicing.

2023-03-01 09:45 UTC, ReimarBauer commented
Hi, this looks like you want to merge develop into stable.

Please compare the needed changes in the patch file I send you. It is much too much, changing now 318 files.

2023-03-01 09:55 UTC, rootxrishabh commented
Accidentally updated the branch using develop, I will fix this.

2023-03-01 10:19 UTC, ReimarBauer commented
please read the patch / diff file again, there is a missing change in the docs dir

2023-03-01 10:34 UTC, ReimarBauer requested changes
compare to the example and adjust accordingly, name ;)
[version_patch.diff.txt](https://github.com/Open-MSS/MSS/files/10859955/version_patch.diff.txt)

2023-03-01 10:34 UTC, ReimarBauer commented on mslib/_tests/test_version.py
> +    :copyright: Copyright 2017 Reimar Bauer, Joern Ungermann
What is your name?

2023-03-01 10:34 UTC, ReimarBauer commented on mslib/_tests/test_version.py
> +    :copyright: Copyright 2017-2022 by the MSS team, see AUTHORS.
change to 2023-2023

because this year it is new

2023-03-01 10:34 UTC, ReimarBauer commented on mslib/_tests/test_version.py
> +    mslib._tests.utils
this is not the name of the test module

2023-03-01 10:34 UTC, ReimarBauer commented on mslib/_tests/test_version.py
> +    This module provides common functions for MSS testing
what is the purpose of the test? This should be in this line. 

When you have imported a module, the doc string is accessible by the `__doc__` method

```
import test_version
print(test_version.__doc__)
```

Our IDEs shows than this information too.

2023-03-01 10:34 UTC, ReimarBauer commented on mslib/_tests/test_version.py
> +        test_version_string()
have a look on the example in the diff file

2023-03-01 10:34 UTC, ReimarBauer commented on mslib/_tests/test_version.py
> +        test_version_string()
usually
```
with pytest.raises():
E       TypeError: raises() missing 1 required positional argument: 'expected_exception'
```

2023-03-02 08:52 UTC, ReimarBauer approved these changes
thx :)

2023-03-02 08:52 UTC, merged

2023-03-02 09:11 UTC, rootxrishabh commented
@ReimarBauer Hey, I learned a lot in this PR, thank you supporting every step of the way : )

2023-03-02 09:39 UTC, ReimarBauer commented
@rootxrishabh You are welcome :)