Added Bug Report, Feature Request and Pull Request Template.
Open-MSS/MSS pull request #1690
Opened 2023-03-05 10:38 UTC by Mr-Sunglasses

Added Bug Report, Feature Request and Pull Request Template for the better standards of the the project and for easily understand the issue or pull request.

2023-03-05 11:04 UTC, ReimarBauer commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- Browser [e.g. chrome, safari]:
because most users need the QT app this line is not needed

2023-03-05 11:06 UTC, ReimarBauer commented on .github/ISSUE_TEMPLATE/feature_request.md
> +## How to test
a feature is something completly new so the test section is not needed

2023-03-05 11:07 UTC, ReimarBauer commented on .github/ISSUE_TEMPLATE/feature_request.md
> +name: Feature request
we lable as enhancement. So I would prefer that name here

2023-03-05 11:11 UTC, ReimarBauer commented on .github/PULL_REQUEST_TEMPLATE.md
> +Describe the steps required to test the changes proposed in the pull request.
not sure about this.

preferable a test added which covers the changes, but not always all can do that.  We mostly accept PR only related to an issue with a description

2023-03-05 11:12 UTC, ReimarBauer commented
good idea.

please add an issue and link it. We use issues also for documentation what we change or introduce.

2023-03-05 11:20 UTC, Mr-Sunglasses commented
> good idea.
> 
> please add an issue and link it. We use issues also for documentation what we change or introduce.

Done, and resolved all issues with this PR 👍🏻

2023-03-06 07:49 UTC, joernu76 requested changes

2023-03-06 07:49 UTC, joernu76 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Any logs (if any) generated in
There seems to be missing some information about logfile-location?

2023-03-06 07:49 UTC, joernu76 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +before creating the pull request to make sure you follow all the standards. -->
Capitalization. What shall the "-->" express?

2023-03-06 07:49 UTC, joernu76 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +fix an issue already created in the repository
punctuation.

2023-05-17 15:24 UTC, ReimarBauer requested changes
pullrequest template and feature_request template look quite similiar from content. A feature request needs a different wording.

we maybe can later copy this from the fs_filepicker after ist was fixed there.

2023-05-17 15:24 UTC, ReimarBauer requested changes
pullrequest template and feature_request template look quite similiar from content. A feature request needs a different wording.

we maybe can later copy this from the fs_filepicker after ist was fixed there.

2023-08-21 19:46 UTC, closed without merging