update
Open-MSS/MSS pull request #1705
Opened 2023-03-20 09:30 UTC by joernu76

2023-03-20 13:52 UTC, ReimarBauer requested changes
At least using sideview is a problem on clicking options - ok

![options_problem](https://user-images.githubusercontent.com/278728/226360325-e5b9737d-8684-4b40-a5fb-548971decc4b.gif)

2023-03-20 13:52 UTC, ReimarBauer commented on mslib/msui/mpl_qtwidget.py
> +    "flightlevels": [],
an old entry was:
https://github.com/Open-MSS/MSS/pull/1705/files#diff-46d3dceb21b8fa62a87ac72721c0c16241048c1eef22ecc21fa3786f282f8f6bL68
"flightlevels": [300, 320, 340]

I'm not verified if that was used, just seen in the review

2023-03-20 16:59 UTC, joernu76 commented
> At least using sideview is a problem on clicking options - ok
> 
> ![options_problem](https://user-images.githubusercontent.com/278728/226360325-e5b9737d-8684-4b40-a5fb-548971decc4b.gif) [ ![options_problem](https://user-images.githubusercontent.com/278728/226360325-e5b9737d-8684-4b40-a5fb-548971decc4b.gif) ](https://user-images.githubusercontent.com/278728/226360325-e5b9737d-8684-4b40-a5fb-548971decc4b.gif) [ ](https://user-images.githubusercontent.com/278728/226360325-e5b9737d-8684-4b40-a5fb-548971decc4b.gif)

Fixed this and some other issues in linear view.

2023-03-20 17:12 UTC, ReimarBauer commented on tests/_test_msui/test_sideview.py
> +# -*- coding: utf-7 -*-
typo?

2023-03-20 17:14 UTC, ReimarBauer requested changes
unicode standard? -8 ?

tests/_test_msui/test_sideview.py

2023-03-22 06:44 UTC, ReimarBauer commented
found a different problem. The stored draw flight track color is not used for the initialization on a restart in the Sideview
also other flight track colors are not used
![color_options_not_used](https://user-images.githubusercontent.com/278728/226822894-59e64501-9d83-48bf-93c1-132d364e9ee0.png)


After clicking options and ok, they are updated
![option_color_not_used](https://user-images.githubusercontent.com/278728/226821954-98bc6d6d-eee7-4b56-b566-8877d3850b87.gif)

in Topview this is doing as expected

2023-03-22 06:45 UTC, ReimarBauer requested changes
see comment example, sideview is not using stored settings on restart

2023-03-22 12:15 UTC, ReimarBauer approved these changes
Thx

2023-03-22 12:16 UTC, merged