Tests added for remote sensing widget
Open-MSS/MSS pull request #1739
Opened 2023-04-16 14:12 UTC by rootxrishabh

fixes #1575

2023-04-16 15:19 UTC, ReimarBauer commented on tests/_test_msui/test_remotesensing.py
> +    :copyright: Copyright 2023 rootxrishabh
maybe you want to add your name to the AUTHORS file?

2023-04-16 15:19 UTC, ReimarBauer commented on tests/_test_msui/test_remotesensing.py
> +app = QtWidgets.QApplication(sys.argv)
see test results, this won't work
https://github.com/Open-MSS/MSS/actions/runs/4713789246/jobs/8359708435?pr=1739#step:9:30

2023-04-17 20:09 UTC, ReimarBauer commented on tests/_test_msui/test_remotesensing.py
> +    :copyright: Copyright 2023 rootxrishabh
thought adding to authors ...

2023-04-17 20:11 UTC, rootxrishabh commented on tests/_test_msui/test_remotesensing.py
> +    :copyright: Copyright 2023 rootxrishabh
I will remove it after checking the test results.

2023-04-17 20:11 UTC, ReimarBauer commented on tests/_test_msui/test_remotesensing.py
> +import sys
there is a pythonic order of imports see PEP8

2023-04-21 10:07 UTC, joernu76 requested changes

2023-04-21 10:07 UTC, joernu76 commented on tests/_test_msui/test_remotesensing.py
> +        self.result_test_tangent_point_coordinates = [(round(x, 2), round(y, 2)) for x, y in
I'd think it is reasonable to store the data only with two significant digits. This is very cluttered and suggests an unneeded precision.

2023-04-21 10:07 UTC, joernu76 commented on tests/_test_msui/test_remotesensing.py
> +        assert round(angle[0], 2) == 106.71
Please use pytest approx
https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest-approx

2023-04-21 10:07 UTC, joernu76 commented on tests/_test_msui/test_remotesensing.py
> +        assert round(angle[0], 2) == 106.71
I'd also suggest to use pytest.mark.parametrize so separate the different tests:
https://docs.pytest.org/en/7.1.x/how-to/parametrize.html#parametrize

2023-04-21 10:07 UTC, joernu76 commented on tests/_test_msui/test_remotesensing.py
>          compute_view_angles = RemoteSensingControlWidget.compute_view_angles
The widget is almost always used. Please define a widget as member in setup, or is there a reason not to?

2023-04-21 10:07 UTC, joernu76 commented on tests/_test_msui/test_remotesensing.py
> +    def test_calc_view_rating(self):
Again, please use "parametrize".

2023-04-29 06:26 UTC, ReimarBauer commented
please have a look on the merge conflict and solve it.

2023-05-10 07:52 UTC, joernu76 approved these changes

2023-05-10 07:52 UTC, merged