Issue1754
Open-MSS/MSS pull request #1757
Opened 2023-04-27 11:45 UTC by joernu76

2023-04-27 13:30 UTC, ReimarBauer requested changes
please send this to stable

2023-04-27 13:31 UTC, ReimarBauer commented on CHANGES.rst
>  =========
there is a missing merge from stable to development. In stable we have this. see PR ;)

2023-04-27 13:39 UTC, ReimarBauer reviewed
tried it, works.

There could be a cosmetic change done. 

The other labels e.g. "Flight Tracks:" and "Open Views:" do endwith a ":". We missed that for "Operations" and "Archived Operations"
 
 
 This could also become a good first issue.

2023-04-27 15:08 UTC, joernu76 commented
Should have gone to stable. now it goes.

2023-04-27 16:23 UTC, ReimarBauer approved these changes, later dismissed
Thx

2023-04-28 12:17 UTC, ReimarBauer commented
after Unarchiving the bold formatted PH1 gets cleared the styles

![problem](https://user-images.githubusercontent.com/278728/235145107-8cd99567-66ee-403a-9eed-381f72196152.png)

2023-04-28 12:17 UTC, ReimarBauer requested changes
see comment

2023-04-28 12:25 UTC, ReimarBauer commented
this needs a refactoring for next major too.
https://github.com/Open-MSS/MSS/blob/develop/mslib/mscolab/models.py#L136

This has to be done there because this will require a database migration too

2023-04-28 12:59 UTC, joernu76 commented
I think that bug was there before and the other pull request #1761 might fix it. At least it solves some related issues...

As you can see from the changes, this PR does not do functional changes and I'd like to keep it this way.

2023-04-28 13:15 UTC, joernu76 commented
> this needs a refactoring for next major too. https://github.com/Open-MSS/MSS/blob/develop/mslib/mscolab/models.py#L136
> 
> This has to be done there because this will require a database migration too

internally, there is a lot of renaming needed, which I mostly defer here to keep the amount of changes to stable minimal.
I will work on fixes in develop as soon as this has been merged and brought into develop.

2023-04-28 13:31 UTC, ReimarBauer commented
This can be used for testing, on an created operation

```
>>> from mslib.mscolab.seed import archive_operation
WARNING:root:Couldn't import mscolab_auth (ImportError:'{No module named 'mscolab_auth'), creating dummy config.
>>> archive_operation("v1","aa@aa")
```

that can be later renamed for toggling the state, currently I got the same situation, I've unarchived all I had

2023-04-28 13:34 UTC, ReimarBauer commented
ok not readed all, can remove my addition, what do you think?

2023-04-28 13:42 UTC, ReimarBauer commented
> I think that bug was there before and the other pull request #1761 might fix it. At least it solves some related issues...
> 
> As you can see from the changes, this PR does not do functional changes and I'd like to keep it this way.

verfied that was before too

2023-04-28 13:43 UTC, ReimarBauer commented
that seed function would be needed to add tests in stable which I also prefer for bug fixes

2023-04-28 13:44 UTC, ReimarBauer approved these changes
ok, does what is expected verified manually

2023-04-28 13:55 UTC, merged