Implement sso test cases
Open-MSS/MSS pull request #1812
Opened 2023-06-25 07:49 UTC by nilupulmanodya

Test cases implementation for the localhost SSO process
We can review  and merge this when https://github.com/Open-MSS/MSS/pull/1811 merged

2023-06-28 18:07 UTC, ReimarBauer requested changes
see comments

2023-06-28 18:07 UTC, ReimarBauer commented on localbuild/meta.yaml
> +    - beautifulsoup4
when this is only needed for tests, please move it to requirements.d/development.txt

2023-06-28 18:07 UTC, ReimarBauer commented on tests/_test_sso_localhost/test_sso_localhost.py
> +def client():
When client is a helper function this should go into tests/utils

2023-06-28 18:07 UTC, ReimarBauer commented on tests/_test_sso_localhost/test_sso_localhost.py
> +    'openssl req -x509 -newkey rsa:4096 -keyout mslib/auth_client_sp/test_key_sp.key '
there we should use a path based on this constant https://github.com/Open-MSS/MSS/blob/develop/tests/constants.py#L48

Maybe you can refactor it to a better identifier name, e.g. just mss ;)

Likly ROOT_DIR is what you want to use then, it is the meaning of root from a pyfilesystem path. 

At all when you use that constant, on each run a new tmp file is used and usually on a reboot that /tmp dir get's cleaned up.

Please don't save files into the mslib dir. Also a relative path is a problem. E.g. when I use the docker container for tests, I can also have a path like: 
`(mss-develop-env) root@d3a9d2e814be:/home/reimar/PycharmProjects/2023/nilupulmanodya/MSS/tests`

2023-06-28 18:07 UTC, ReimarBauer commented on tests/_test_sso_localhost/test_sso_localhost.py
> +            response = subprocess.run(['curl', '-s', '-o', '/dev/null', '-w', '%{http_code}', 'http://localhost:5000/'], capture_output=True)
curl maybe can become replaced by the requests module?

2023-06-28 18:07 UTC, ReimarBauer commented on tests/_test_sso_localhost/test_sso_localhost.py
> +    process_start_idp = subprocess.Popen(['python', 'mslib/idp/idp.py', 'idp_conf'])
That may can become replaced to something similiar to https://github.com/Open-MSS/MSS/blob/develop/tests/utils.py#L212 ?

2023-06-28 18:07 UTC, ReimarBauer commented on tests/_test_sso_localhost/test_sso_localhost.py
> +    process_start_idp.kill()
A bit this also looks like it can be part of a Test Class with 
setUp and tearDown

2023-06-28 18:07 UTC, ReimarBauer commented on tests/_test_sso_localhost/test_sso_localhost.py
> +    # Delete the generated files
see above these files have to go into a defined tmp dir

2023-06-28 18:07 UTC, ReimarBauer commented on tests/_test_sso_localhost/test_sso_localhost.py
> +    assert None is db.session.commit()
there should be also a check that the user is in the db.

2023-06-28 18:07 UTC, ReimarBauer commented on tests/_test_sso_localhost/test_sso_localhost.py
> +    subprocess.run(process_gen_crt_key_idp, shell=True, check=True)
a further step can be to use pyopenssl 
- https://anaconda.org/conda-forge/pyopenssl
- https://www.pyopenssl.org/en/latest/

2023-07-03 09:01 UTC, matrss reviewed
I don't quite understand the reasoning for the `TEST_CASES_ENABLED` env variable and the special handling of `key_file` and `cert_file` when loading the yaml config. Can't we just have a testing-specific `saml2_backend.yaml` which points to the correct key and cert for testing and ditch the special handling in `get_crt_key()` and when loading yaml configuration file?

2023-07-03 09:01 UTC, matrss commented on tests/_test_sso_localhost/test_sso_localhost.py
> +    process_start_idp.kill()
A pytest fixture as a generator, like it is done here, seems to be the recommended/idiomatic way to do setup and teardown stuff in pytest. pytest also supports `setup_{module,class,method}` and corresponding teardown functions, but according to the documentation fixtures are recommended over those. `setUp` and `tearDown` seem to be names used in `unittest`, which we should avoid.

Also, this fixture could be used in other tests where we might need the IdP/SP running, but aren't actively testing those. That would be harder with a class-based structure.

Therefore I'd argue to keep this fixture-based structure.

Maybe it would be beneficial to split the fixture up into two fixtures though, one for the IdP and one for the SP. From my understanding it would make sense to merge the SP functionality into the existing mscolab server component at some point, and two fixtures would be easier to deal with then.

2023-07-19 06:08 UTC, ReimarBauer commented
@nilupulmanodya please look on the merge conflicts too ;)

2023-07-19 06:12 UTC, ReimarBauer commented on tests/_test_sso_localhost/test_sso_localhost.py
> +import os
this needs also a file header, see our template ;)

2023-07-21 19:19 UTC, ReimarBauer requested changes
we need all certs and configfiles outside of the mslib dir created and stored. You can use constants or config values to have variables to point on them. We need this also for configuring after the software is installed not only for testing. But testing is then close to a deployed server. 
For example a default dir outside of mslib could be ~/mscolab.  On testing it is a tmp dir see the conftest.py example. 


[conftest.py.txt](https://github.com/Open-MSS/MSS/files/12131707/conftest.py.txt)

Afterwards when you have a working conftest and the pathes of the files needed configurable start with the simple tests. e. g.

 
```
from mslib.auth_client_sp.app.app import rndstr, get_idp_entity_id

def test_rndstr():
    assert rndstr() is not None
    assert len(rndstr()) == 16

def test_get_idp_entity_id():
    assert get_idp_entity_id() is not None
```

When you use a tests dir you can setup there an conftest.py, incomplete example above, where you can setup all certs etc. The metadata file could be created by a function test util because we have the cert and we don't need the server to be started to fetch it.

2023-11-11 13:15 UTC, closed without merging

2023-11-11 13:15 UTC, nilupulmanodya commented
Closing this PR, since we are no longer using `auth_client_sp` .. will update other functional test cases with upcoming PRs :)