web browser implementation
Open-MSS/MSS pull request #1814
Opened 2023-07-07 04:55 UTC by nilupulmanodya

QT web browser UI :

![image](https://github.com/Open-MSS/MSS/assets/57173445/da33ce47-1548-42c0-a0e5-cad61a42a5ba)

2023-07-11 07:47 UTC, matrss commented
I am not sure if I misunderstand the login flow in some way, but I would have some security concerns if we are using our own browser window instead of the users default browser: as a user using some IdP, e.g. the Helmholtz AAI or even GitHub (though that is not using SAML), I would want my password for that IdP to never be accessible to the SP, i.e. MSS/mscolab in our case. This is especially important if the IdP is also used to login into other applications, which is basically always the case. If we introduce our own QT browser window and ask the user to login to their IdP in that window we would now get at least the possibility to see the users password, even if we do not abuse that. As a user I trust my browser with my login credentials, but not some random window pretending to be a browser. Therefore I'd prefer to use the installed default browser instead of rolling our own.

2023-07-11 10:05 UTC, ReimarBauer commented
> I am not sure if I misunderstand the login flow in some way, but I would have some security concerns if we are using our own browser window instead of the users default browser: as a user using some IdP, e.g. the Helmholtz AAI or even GitHub (though that is not using SAML), I would want my password for that IdP to never be accessible to the SP, i.e. MSS/mscolab in our case. This is especially important if the IdP is also used to login into other applications, which is basically always the case. If we introduce our own QT browser window and ask the user to login to their IdP in that window we would now get at least the possibility to see the users password, even if we do not abuse that. As a user I trust my browser with my login credentials, but not some random window pretending to be a browser. Therefore I'd prefer to use the installed default browser instead of rolling our own.

It is not planned to send your password to our mscolab SP.  The QT Webbrowser behaves like following examples, besides that we won't show the direct login on the mscolab server site as we have to on nextcloud.

- Example show how to contact over a server the AAI
![phileas1](https://github.com/Open-MSS/MSS/assets/278728/718dc286-697c-4f9c-8c81-9d354d76c040)

- use the AAI by its web service
![phileas2](https://github.com/Open-MSS/MSS/assets/278728/3b747794-28f8-4bb9-a8e3-1bcfa29d9679)

similiar to our nextcloud implementation we will get some response to see that the authentication was valid.
This part is yet not implemented.

There may be a user config to switch to the platforms browser and a description how to manually "login" by that. But first lets implement the authentication proccess at all. I think switching the browser afterwards is an easier task.

2023-07-11 10:43 UTC, matrss commented
> It is not planned to send your password to our mscolab SP.

I am aware of that. My issue is that due to the QT webbrowser being a part of the MSS application running on the users device, it is technically possible to read out the password field of the IdP when it is filled in. If we would use the platforms browser, i.e. an application that we do not directly control, we wouldn't even have the possibility to access that information. As a user I'd prefer if a password leak was impossible (or rather dependent on the security of my preferred browser) instead of needing to trust some application developer to not do something shady. Not that I would be concerned about that with MSS, but in general (I have seen android apps that open PayPal for payments in an in-app browser and that seemed like a very shady thing to do, considering that those app developers could then inject arbitrary JS into the shown PayPal login page AFAIK, just to give an example).

> There may be a user config to switch to the platforms browser and a description how to manually "login" by that. But first lets implement the authentication proccess at all. I think switching the browser afterwards is an easier task.

That seems reasonable. For portability and/or testing purposes I see some value in having our own web browser window, e.g. for programmatic login to our testing IdP when testing this functionality.

2023-07-19 05:48 UTC, ReimarBauer requested changes
see my comments

2023-07-19 05:48 UTC, ReimarBauer commented on mslib/msui/msui_web_browser.py
> +        self.browser_storage_folder = scriptdir + os.path.sep + '/.cookies'
this should be based on  constants.MSUI_CONFIG_PATH instead of scriptdir

2023-07-19 05:48 UTC, ReimarBauer commented on mslib/msui/msui_web_browser.py
> +        scriptdir = os.path.dirname(os.path.realpath(__file__))
use constants.MSUI_CONFIG_PATH

2023-07-19 05:48 UTC, ReimarBauer commented on mslib/msui/msui_web_browser.py
> +class QTWebBrowser(QMainWindow):
the name should get a relation to MSUI, e.g MSUIWebBrowser. compare to class names in msui for the main window

2023-07-19 05:50 UTC, ReimarBauer commented
This is a good addition for testing this, as we don't need to install firefox etc. into our docker container and have a clear state of a browser.

It maybe become also interesting for using our documentation locally.

2023-07-24 11:22 UTC, ReimarBauer approved these changes
Header can be updated when it is used for tests

2023-07-24 11:22 UTC, ReimarBauer commented on mslib/msui/msui_web_browser.py
> +    QTWebBrowser for the SSO process.
the formatting is quite condensed but not that important

after a module import you do read it by help()

```
from mslib.msui import msui_web_browser
help(msui_web_browser)
```

2023-07-24 12:16 UTC, matrss approved these changes

2023-07-25 16:13 UTC, ReimarBauer approved these changes
Thx

2023-07-25 20:17 UTC, merged