👍 Corrected the spelling mistake in TopView from Multiple FLightpath…
Open-MSS/MSS pull request #1845
Opened 2023-07-30 09:40 UTC by ambiguousphoton

…s to Multiple Flightpath.

2023-07-30 09:41 UTC, ambiguousphoton commented
ok

2023-07-31 07:52 UTC, joernu76 commented on NOTICE
> +To draw airports on the w we use the services provided by ourairports
This doesn't look right... Same below.

2023-07-31 07:52 UTC, joernu76 requested changes
Please fix the newly introduced spelling mistake in NOTICE.

2023-07-31 11:51 UTC, ambiguousphoton commented
Ok

2023-07-31 19:48 UTC, closed without merging