Made MSColab timeout configurable.
Open-MSS/MSS pull request #1916
Opened 2023-08-21 05:33 UTC by joernu76

Fix #1915

2023-08-21 19:30 UTC, ReimarBauer requested changes
see comment, the value is two elements, so list_options fits better

2023-08-21 19:30 UTC, ReimarBauer commented on mslib/utils/config.py
> +        'MSCOLAB_timeout',
This should be added to the list_option_structure, because of two values.

We need to review this at all. But I think it matches better there. 

e.g. file_picker_default is only a checkbox boolean, data_dir is one value.

We don't destinguish from the UI between list and tuple, 2 values -> list

2023-08-21 19:42 UTC, joernu76 commented on mslib/utils/config.py
> +        'MSCOLAB_timeout',
with the list-options it might complain about two same values?

2023-08-21 20:45 UTC, ReimarBauer commented on mslib/utils/config.py
> +        'MSCOLAB_timeout',
ok, we keep it as it is.

this needs a kind of test later to not doing something unexpected

2023-08-22 16:35 UTC, ReimarBauer commented
I agree with this but want to understand what is the difference to the other option first.

2023-08-23 14:20 UTC, ReimarBauer approved these changes

2023-08-24 05:21 UTC, merged