Remove redundant calls to "operations"
Open-MSS/MSS pull request #1941
Opened 2023-08-25 00:26 UTC by joernu76

Pass on previous results to subsequent functions, disable unnecessary request triggers.

Fix #1940

2023-08-25 00:27 UTC, joernu76 commented
This seems to work nicely by removing 5-6 redundant requests. Still pretty slow (with our current distance), but better.
I am not very familiar with that part of the code, please review thoroughly.

2023-08-25 07:52 UTC, ReimarBauer commented
please verify with a VPN if you are not throttled again.

2023-08-25 07:56 UTC, ReimarBauer requested changes
ANY is not a name of a category, it should show ALL existing operations. its meaning is "*". 
The sign only would be on the button invisible.

2023-08-25 07:58 UTC, ReimarBauer commented
I have also a category "example" I assume that the OP is archived. We maybe should exclude archived operations. I guess this was same behaviour before this change.

2023-08-25 18:01 UTC, joernu76 commented
I am *not* using the ridiculously slow WLAN, but our much faster house Wifi and/or Georgs Labor-LAN and FZJ-VPN.
A request takes about 1s (compared to >3s for the strange hangar-guest-Wifi).
For the given amount of categories, this Pull request removes ca. 6 redundant "operations" request, removing about 6s from the >14s login-time.

This change introduces some added complexity, but in particular the automatically triggered operation-calls when populating the category list should go in any way (the clear and each add call as well as the final select, each trigger an operations-request).

2023-08-25 18:50 UTC, ReimarBauer commented
We need to remove ANY or make it list all operations, or find another way to list all existing.

2023-08-27 13:27 UTC, ReimarBauer approved these changes
added ANY functionality and a test for that

2023-08-27 17:28 UTC, merged