Some tidying up of handling imports in MSCOlab
Open-MSS/MSS pull request #1962
Opened 2023-08-28 20:11 UTC by joernu76

The connect seems to be wrong, a disconnect seems in order. It might be better to not create a new waypoint_model, but change the content of the old one?
Either way, with these streamlining, the error was not reproducible anymore. Since it was sporadic before, this might be by chance.

See #1960

**Purpose of PR?**:

Fixes #

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Does this PR results in some Documentation changes?**
_If yes, include the list of Documentation changes_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (Non-API breaking changes that adds functionality)
- [ ] PR Title follows the convention of  `<type>: <subject>`
- [ ] Commit has unit tests

2023-08-29 08:44 UTC, ReimarBauer commented
Hmm, I assume you mean this,

![same_problem](https://github.com/Open-MSS/MSS/assets/278728/571086e1-74d0-4875-afe5-bb63eeb9286c)

so it is reproduced and still open

2023-08-29 08:51 UTC, ReimarBauer commented
checking without IDE, this might behave different

2023-08-29 09:26 UTC, ReimarBauer commented
I assume that some of my other running apps on my desktop blocks this by something similiar to this 
https://github.com/Open-MSS/MSS/issues/1591

2023-08-29 09:38 UTC, ReimarBauer commented
Update: on doubleclick, the QT file browser selects a file and closes. Then the main view is on top and the selected import dialog is behind this UI **hidden**

![wrong_widget_inf_front](https://github.com/Open-MSS/MSS/assets/278728/8483ce4b-1ee7-4dd2-8193-dc21a3ce515b)

2023-08-29 09:45 UTC, ReimarBauer requested changes
please have a look if you could easily bring the import dialog always in front after a file was selected.

It is not easy to recognize.

2023-08-31 15:39 UTC, joernu76 commented
Mmmh. This cannot happen on *my* WMS because it is tiling. Thus I cannot test this easily, at least today.
However, I observed the waypoints changing and reverting, which I attribute to some strange timings and the exchange of the waypoint model (I believe it'd be better to change the waypoints within, but this is a bigger change I currently do not have time for).
This merge request also doesn't close the issue, as I think it makes things safer, but does not necessarily fixes (all) problems.

2023-08-31 16:01 UTC, ReimarBauer approved these changes
needs a review before release, but good enough for now

2023-08-31 16:03 UTC, merged