Fix messagebox warnings
Open-MSS/MSS pull request #1967
Opened 2023-08-30 10:41 UTC by matrss

**Purpose of PR?**:

Fixes #1957. This turns the warning when there are unhandled message boxes left into actual errors. I also started to fix those errors, but that is still WIP.

**Does this PR introduce a breaking change?**

No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Does this PR results in some Documentation changes?**
_If yes, include the list of Documentation changes_

**Checklist:**
- [X] Bug fix. Fixes #1957
- [ ] New feature (Non-API breaking changes that adds functionality)
- [ ] PR Title follows the convention of  `<type>: <subject>`
- [ ] Commit has unit tests

2023-08-30 13:23 UTC, matrss commented
Started out with 40 errors, down to 20 now.

2023-08-30 19:05 UTC, ReimarBauer commented
@matrss maybe merge the refactor_tests_and_setup into yours.

In the mscolab tests and mscolab are a way more broken hidden by the mocking in conftest.

2023-08-31 11:07 UTC, matrss commented
There is 2 errors left to go. One of those is an unexpected None value, but it happens in the teardown and I did not yet understand why. The other is this `AttributeError: 'NoneType' object has no attribute 'flighttrack_model'`. I tried cherry-picking 35a0ebacad8c7da777792db5011830d1e0b4087b, but that just breaks more tests.

2023-08-31 12:26 UTC, ReimarBauer commented
> There is 2 errors left to go. One of those is an unexpected None value, but it happens in the teardown and I did not yet understand why. The other is this `AttributeError: 'NoneType' object has no attribute 'flighttrack_model'`. I tried cherry-picking [35a0eba](https://github.com/Open-MSS/MSS/commit/35a0ebacad8c7da777792db5011830d1e0b4087b), but that just breaks more tests.

Likly the "pytest" check has masked several other incomplete setup of msui.MSUIMainWindow(mscolab_data_dir=mscolab_settings.MSCOLAB_DATA_DIR)

The self.window.create_new_flight_track() was missing in any mscolab ui test.

The NoneType comes likly from this missing switch to local. Because we need always a waypoint table.

https://github.com/Open-MSS/MSS/pull/1968/files#diff-8bb1b53508f9fe252a80649575f92b7aa4756be8dda54c217a7c1d9063d6b0c5R1059

2023-08-31 14:55 UTC, matrss commented
OK, looks like it is just one issue left: for some reason in the teardown code of `Test_MscolabAdminWindow`  after `self.window.mscolab.logout()`, which unsets `self.window.mscolab.mscolab_server_url`, there is another call to `render_new_permission` triggered by `QtWidgets.QApplication.processEvents()`. This method the complains about `mscolab_server_url` being None. This issue fails between 0 and 3 tests on my system.

2023-08-31 15:31 UTC, ReimarBauer commented
I stopped after some tests completed, the image is about 30% of _test_msui

the main UI is not closed (hide) and at  least 2 rename boxes are kept.

![msui_test](https://github.com/Open-MSS/MSS/assets/278728/6ed620b8-95de-448e-bdce-abc3cb6fba2b)

the Ui can get removed from the screen by an addition to the teardown https://github.com/Open-MSS/MSS/pull/1968/files#diff-d112e799e3e5bb46f90f69735aa878cb4a2d0cb453816f56edafca3935236fc4R88

One of the "descriptions is updated.." is a c/p bug currently description and category update have the same message,

https://github.com/Open-MSS/MSS/pull/1968/files#diff-8bb1b53508f9fe252a80649575f92b7aa4756be8dda54c217a7c1d9063d6b0c5R1137

these boxes are "information" not "question"

Maybe take the unhandled, I assume three of these boxes, and the rest can be done later.

2023-09-01 08:04 UTC, matrss commented
Right, I think these windows remain because I removed the code that just closes all remaining widgets from the fixture in conftest. Ideally, I think this fixture should look like this:
```
@pytest.fixture(autouse=True)
def fail_if_open_widgets_left():
    """Fail a test if there are any Qt widgets left open at the end
    """
    yield
    widgets = set(QtWidgets.QApplication.topLevelWindows() + QtWidgets.QApplication.topLevelWidgets())
    assert len(widgets) == 0, "There are Qt widgets left open at the end of the test!"
```
but there are many more widgets and windows in that and I think some of those are memory leaks in mss itself (e.g. there is a hidden "Browse archived operations" window that is not closed properly with the main window when I just run `test_login`).

These were previously not catched by the mocking of the message boxes and then just silently closed.

2023-09-01 08:15 UTC, matrss commented
> these boxes are "information" not "question"

These boxes are `QErrorMessage`s instead of any `QMessageBox`, that is why they are not currently failing the tests.

2023-09-01 08:53 UTC, ReimarBauer commented
> > these boxes are "information" not "question"
> 
> These boxes are `QErrorMessage`s instead of any `QMessageBox`, that is why they are not currently failing the tests.

I think that is the wrong type QErrorMessage for the kind of information.

2023-09-01 08:56 UTC, ReimarBauer commented
> Right, I think these windows remain because I removed the code that just closes all remaining widgets from the fixture in conftest. Ideally, I think this fixture should look like this:
> 
> ```python
> @pytest.fixture(autouse=True)
> def fail_if_open_widgets_left():
>     """Fail a test if there are any Qt widgets left open at the end
>     """
>     yield
>     widgets = set(QtWidgets.QApplication.topLevelWindows() + QtWidgets.QApplication.topLevelWidgets())
>     assert len(widgets) == 0, "There are Qt widgets left open at the end of the test!"
> ```
> 
> but there are many more widgets and windows in that and I think some of those are memory leaks in mss itself (e.g. there is a hidden "Browse archived operations" window that is not closed properly with the main window when I just run `test_login`).
> 
> These were previously not catched by the mocking of the message boxes and then just silently closed.

I'm ok with such fixtures, when we don't see these problems we likly won't work on those.

2023-09-01 09:32 UTC, matrss commented
> I'm ok with such fixtures, when we don't see these problems we likly won't work on those.

I agree, but this fixture would lead to > 300 failed tests (basically all that involve the UI?). I think that is to much to handle in this one PR.

> The teardown of many of the tests got improved in the other branch. At least there remains nothing visible.

Nothing visible is not enough, unfortunately. In the `test_login` test case for example there are 16 widgets left, but hidden, that did not get removed by the teardown code.

I think I will reintroduce the closing code to the fixture here for now and we can tackle this in a follow up PR.

2023-09-01 15:03 UTC, matrss commented
The remaining issue is this: on teardown of `test_add_permissions` there is a call to `self.window.mscolab.logout()`. This method first sets `self.mscolab_server_url = None` and then at a later point disconnects the socketio socket: `self.conn.disconnect()`. This disconnect queues up a qt event which makes the application call `render_new_permission` the next time `processEvents()` is called. But at that point the logout already unset the mscolab server url, which leads to
```
  File "/__w/MSS/MSS/mslib/msui/mscolab.py", line 1391, in render_new_permission
    r = requests.get(self.mscolab_server_url + '/user', data=data,
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Moving the disconnect call to somewhere before un-setting the url and calling `processEvents` immediately after fixes this issue.

2023-09-01 15:27 UTC, ReimarBauer commented
This one should be checked if we need a backport to stable. I've not seen it in normal usage yet.
https://github.com/Open-MSS/MSS/pull/1967/commits/0f5c937de9aca3b835e4a16e50308d9ed104cfe9

2023-09-03 06:25 UTC, ReimarBauer requested changes
Please add the comment, so that we later at least for a release check for this again.

2023-09-03 06:25 UTC, ReimarBauer commented on tests/_test_msui/test_mscolab.py
> +        modify_config_file({"MSS_auth": {self.url: self.userdata[0]}})
less mocking :)

some tests have more than one QMessageBox and we can't mock them differently

2023-09-03 06:25 UTC, ReimarBauer commented on mslib/msui/mscolab.py
> +        QtWidgets.QApplication.processEvents()
Please add a comment before the processEvents() line
e.g.

ToDo review why the code gets blocked and refactor this part


The problem with this is that we not know where it hangs and this cause needs to be resolved.
In the "released users code" we should never need QtWidgets.QApplication.processEvents()


good article about qthreadpool, I don't see from our site a thread involved. The article describes the behaviour.
https://www.pythonguis.com/tutorials/multithreading-pyqt-applications-qthreadpool/

2023-09-03 06:27 UTC, ReimarBauer commented
> This one should be checked if we need a backport to stable. I've not seen it in normal usage yet. [0f5c937](https://github.com/Open-MSS/MSS/commit/0f5c937de9aca3b835e4a16e50308d9ed104cfe9)

Because of the QApplication.processEvents() we better don't add this to stable.

2023-09-05 06:55 UTC, matrss commented
> Because of the QApplication.processEvents() we better don't add this to stable.

Would that be a blocker? We have a call to that method in other places (in `msui/mscolab.py` and `msui/mpl_qtwidget.py`) too, but I have no experience with qt. Anyway, I dug a bit deeper and just moving that section up and adding the `processEvents` call is just hiding the issue, not fixing it.

The issue is a race condition caused by this:
1. the test adds users to an operation in the admin interface
2. this calls `add_selected_users`, which makes a post request to `<mscolab_server_url>/add_bulk_permissions`
3. on the server side on success the handler for that request triggers a `new-permission` signal via socketio
4. on the client side receiving this signal triggers the `signal_new_permission` pyqtSignal
5. in `MSUIMscolab` the `render_new_permission` slot is connected to the signal from 4. and therefore gets called

The problem then is that the test runs so fast that between 3. and 4. it is already in the teardown phase and has called the `logout` method, which unsets the server url. Then in 5. we see this issue where the url is None.

My fix so far just hides this, but does not resolve the issue.

It is very unlikely to hit this issue in normal usage, so I don't think we have to look at this on stable. If you add a delay right before emitting the pyqt signal in the socketio handler, then you can recreate the issue interactively though.

I think a proper fix would be to stop the socketio handlers in `ConnectionManager` from emitting pyqt signals after socketio was disconnected, since that does not make much sense anyway. I'll take a look at how that could be done.

2023-09-05 09:20 UTC, matrss commented on tests/_test_msui/test_mscolab.py
> +        modify_config_file({"MSS_auth": {self.url: self.userdata[0]}})
Well, we could, if those message boxes are the result of different lines of code in the test. `mock.patch` can be used as a context manager as well, not just as a decorator to the test function. Still, avoiding the message box entirely if we are not explicitly testing it is the better approach IMHO.

2023-09-05 09:28 UTC, matrss commented
I fixed it properly (I think?) now, removing the usage of `processEvents`. This should address the remaining comments.

2023-09-06 06:27 UTC, ReimarBauer commented on mslib/utils/airdata.py
> +        else:
this prior indenting was correct. The reason is to show to the user that the requested files has no data and is therefore not shown.

we use seldom the for/else clause,  https://book.pythontips.com/en/latest/for_-_else.html

Without this there is no messageBox shown like 
![hint](https://github.com/Open-MSS/MSS/assets/278728/887e1c9d-fec7-456e-a5ba-9a15daf7da19)

This is not that comfortable for a user, but when this gets improved it maybe should not done in this PR?

2023-09-06 06:34 UTC, ReimarBauer commented on tests/_test_utils/test_airdata.py
> +    infobox.assert_called_once_with(None, 'No Airspaces data in file:', 'bg_asp.xml')
once the data gets updated the test will fail.

2023-09-06 06:37 UTC, ReimarBauer commented on mslib/utils/airdata.py
> +        else:
should have looked into the file downloaded. 

110238 Sep  1 10:36 ae_asp.xml

I agree to the change.

2023-09-06 06:39 UTC, ReimarBauer commented on mslib/utils/airdata.py
> +        else:
later we need some kind of feedback to the user, that his selection is not what he gets shown on the map.

2023-09-06 06:55 UTC, matrss commented on tests/_test_utils/test_airdata.py
> +    infobox.assert_called_once_with(None, 'No Airspaces data in file:', 'bg_asp.xml')
The only possible test failure I see that shouldn't be one is if the file name of the data changes. So, the last argument could be changed to `mock.ANY`. Is that what you mean?

2023-09-06 07:04 UTC, ReimarBauer approved these changes
Thx

2023-09-06 07:07 UTC, ReimarBauer commented on tests/_test_utils/test_airdata.py
> +    infobox.assert_called_once_with(None, 'No Airspaces data in file:', 'bg_asp.xml')
I removed the message because I forgot abotu, that we have done a mock of the data containing. So that won't happen.

2023-09-06 07:13 UTC, merged

2023-09-06 07:14 UTC, matrss commented on tests/_test_utils/test_airdata.py
> +    infobox.assert_called_once_with(None, 'No Airspaces data in file:', 'bg_asp.xml')
Ah OK, that makes sense.