removing pinned xmlschema
Open-MSS/MSS pull request #2117
Opened 2023-12-12 11:41 UTC by ReimarBauer

**Purpose of PR?**:

Fixes #2056 

When the xmlschema works here we can update our dockerimages for testing to miniforge3 too

2024-08-05 13:59 UTC, matrss submitted a review, later dismissed

2024-08-05 14:01 UTC, matrss requested changes
This should go to stable.

Again, the age old issue of having two development branches...

2024-08-05 16:57 UTC, ReimarBauer commented
thx. changed the issue MS too.

2024-08-05 18:57 UTC, ReimarBauer commented
puh, only coveralls ...

2024-08-06 08:17 UTC, matrss approved these changes

2024-08-06 08:18 UTC, merged