refactor: Renamed USE_SAML2 to use_saml2
Open-MSS/MSS pull request #2141
Opened 2024-01-09 19:41 UTC by Beeram12

renamed USE_SAML2 to use_saml2 lowered all .

Fixes #2132

2024-01-09 21:40 UTC, ReimarBauer requested changes
Please rename only the USE_SAML2 in the json output. Not any constant we have.

2024-01-09 21:41 UTC, ReimarBauer commented on mslib/mscolab/server.py
> +                'use_saml2': mscolab_settings.use_saml2
this is json :)

2024-01-09 21:42 UTC, ReimarBauer commented on mslib/mscolab/server.py
> +if mscolab_settings.use_saml2:
this is a constant, this should not be renamed

2024-01-09 21:42 UTC, ReimarBauer commented on mslib/mscolab/mscolab.py
> +                    - Ensure that use_saml2 is set to True.
this is not json

2024-01-09 21:42 UTC, ReimarBauer commented on mslib/mscolab/conf.py
> +    use_saml2 = False
this is not json

2024-01-16 14:36 UTC, ReimarBauer commented on mslib/mscolab/conf.py
> +    use_saml2 = False
Do you still work on this @Beeram12  ?

2024-01-16 14:45 UTC, Beeram12 commented on mslib/mscolab/conf.py
> +    use_saml2 = False
@ReimarBauer Sorry for the delay,I am unaware of json format so I couldn't give update regarding this but will come up with right pull request.Kindly forgive me for many mistakes I am a beginner to open source.

2024-01-16 15:20 UTC, ReimarBauer commented on mslib/mscolab/conf.py
> +    use_saml2 = False
Only where we use the json module you need to change it. Not on all places. 

https://www.w3schools.com/python/python_json.asp

2024-01-16 15:54 UTC, closed without merging