Fix: Scheduled test now triggers testing-stable.yml using workflow_dispatch
Open-MSS/MSS pull request #2196
Opened 2024-02-10 20:17 UTC by rohit2p

**Purpose of PR?**: This pull request addresses the issue where the scheduled test was running the `testing.yml` workflow from the develop branch but using the container image for the stable branch. This was incorrect behavior.

Fixes #2172 

Modified the` testing-scheduled.yml` workflow on the develop branch to directly trigger the `testing-stable.yml` workflow using the `benc-uk/workflow-dispatch@v1.2.2 action.`

This change was made to work directly on the develop branch.

**Checklist:**
- [ X] Bug fix. Fixes #2172

2024-02-12 12:09 UTC, matrss requested changes
I left a few comments. In addition to those the testing-stable.yml workflow on the stable branch would need to include the `workflow_dispatch:` trigger. Since that is on a different branch it must happen in an additional PR, unfortunately.

2024-02-12 12:09 UTC, matrss commented on .github/workflows/testing-scheduled.yml
> +  trigger_stable_test:
```suggestion
  trigger-testing-stable:
```

Just to keep a somewhat consistent naming scheme.

2024-02-12 12:09 UTC, matrss commented on .github/workflows/testing-scheduled.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-latest
    permissions:
      actions: write
```

While testing I found out that this permission is required to be able to use the runner token to trigger another workflow.

2024-02-12 12:09 UTC, matrss commented on .github/workflows/testing-scheduled.yml
> +          workflow: testing-stable
```suggestion
          workflow: testing-stable.yml
```

This can be either the filename of the workflow or the full name specified at the top of the workflow file. I think I prefer using the filename.

2024-02-12 18:26 UTC, rohit2p commented
@matrss i have some question, Do you prefer me to create a separate branch form the stable branch for this new PR or should i directly work on stable. Because stable branch defines the workflow for stable tests. Modifying this file directly could break the existing stable tests that's way i was confused. 
also while adding the trigger is this how the code should look like?? 
```
on:
  schedule:
    - cron: '30 5 * * 1'  # Existing schedule trigger
  workflow_dispatch:      # Add the workflow_dispatch trigger
    jobs:     
      test-stable-scheduled:
        uses: 
          ./.github/workflows/testing.yml
# Rest of the code as it is
```
or do i need to add permission or any requirement  like this?
```
on:
  schedule:
    - cron: '30 5 * * 1'
  workflow_dispatch:
    permissions:
      actions: write  
```

2024-02-13 08:43 UTC, matrss commented
> Do you prefer me to create a separate branch form the stable branch for this new PR or should i directly work on stable. Because stable branch defines the workflow for stable tests. Modifying this file directly could break the existing stable tests that's way i was confused.
> the last tym when you said it need to go to develop branch i think misunderstood you and i thought you are saying me to directly work on develop branch.

What I meant with "it needs to go to develop" is that this change to the scheduled workflow ultimately needs to go into the develop branch of Open-MSS/MSS (i.e. this repository). This would happen through this PR here. What the source branch of the PR is (in this case the develop branch of your fork of this repository) is usually not important, although for my own stuff I prefer to use feature branches named after what they implement.

So what I meant regarding stable is that ultimately the `testing-stable.yml` workflow on the stable branch of Open-MSS/MSS needs to have the workflow_dispatch event added so that it can be triggered by the scheduled workflow running on develop.

> also while adding the trigger is this how the code should look like??
> 
> ```
> on:
>   schedule:
>     - cron: '30 5 * * 1'  # Existing schedule trigger
>   workflow_dispatch:      # Add the workflow_dispatch trigger
> 
> jobs:     
>   test-stable-scheduled:
>     uses: 
>       ./.github/workflows/testing.yml
> # Rest of the code as it is
> ```

This, but in `testing-stable.yml` instead of `testing-scheduled.yml`.

To explain what it does:
The
```
on:
  workflow_dispatch:
```
part tells GitHub Actions that the workflow that it is in can be started through a workflow_dispatch event. The benc-uk/workflow-dispatch action uses this event type to trigger an execution of that workflow. Therefore the workflow that is being started needs to "react" to this type of event.

That is also why it needs to go into stable: the `testing-scheduled.yml` workflow triggers the `testing-stable.yml` workflow on the stable branch to run. For this to successfully happen the `testing-stable.yml` workflow on the stable branch needs to be startable through the workflow_dispatch event.

> or do i need to add permission or any requirement like this?
> 
> ```
> on:
>   schedule:
>     - cron: '30 5 * * 1'
>   workflow_dispatch:
>     permissions:
>       actions: write  
> ```

No, the permission just need to be set on the job that uses the benc-uk/workflow-dispatch action (as it now already is), so that this action is allowed to start another workflow run through the workflow_dispatch event.

Does that clarify things a bit?

2024-02-13 09:36 UTC, matrss requested changes

2024-02-13 09:36 UTC, matrss commented on .github/workflows/testing-scheduled.yml
> +        actions: write
```suggestion
      actions: write
```

This should just be indented with two spaces more compared to the previous line, to stay consistent with the rest of the file.

2024-02-13 17:52 UTC, rohit2p commented
Yes, Thank you for your guidance!
Does now everything look cool?

2024-02-14 14:35 UTC, matrss approved these changes
Looks good to me. Thanks a lot for the PR! There is a conflict between this PR and Open-MSS:develop, which is caused by a recent commit on develop (3a0eb968516da8714361e1f284bd955715833cf4) that also touched the testing-scheduled.yml workflow. If you want to fix that conflict yourself feel free to do so, otherwise this could be done when merging as well.

I've tested this change on my fork of MSS and it works so far:
https://github.com/matrss/MSS/actions/runs/7902483658
This workflow run triggered a run of testing-stable.yml that ran on stable as it should:
https://github.com/matrss/MSS/actions/runs/7902485837

@ReimarBauer what do you think about this change? It would need to be merged together with #2197.

2024-02-14 18:14 UTC, rohit2p commented
I've resolved the conflict in the testing-scheduled.yml file by keeping the "trigger-testing-stable" job from the develop branch.

I removed the unused section related to the "test-stable-scheduled" job and cleaned up the conflict markers. Please review the changes and let me know if everything looks good.

2024-02-15 08:24 UTC, ReimarBauer commented
#2197 shows a coredump

2024-02-15 08:33 UTC, matrss commented
> #2197 shows a coredump

See my comment in that PR.

2024-02-15 13:57 UTC, merged