CI overhaul
Open-MSS/MSS pull request #2298
Opened 2024-03-26 15:13 UTC by matrss

This removes the docker image logic from the CI setup and instead replaces it with a setup based on pixi. As part of that it moves the dependency specification from localbuild/meta.yaml to pixi.toml and pixi.lock. This turns the MSS repository into a single source of truth for both the application code as well as the development environment (whereas the latter was previously only specified in the docker images, and not reproducible in any way).

Setting up a development environment is as simple as installing pixi and running `pixi shell` (or `pixi run <cmd>`, or `pixi install` to just create the environment, etc.). This environment will, by construction, be the same that is used in the CI as well (modulo platform differences).

There is a new workflow that periodically (once a week on Monday) recreates the pixi lockfile and opens a PR for that update. The checks in that PR essentially serve as a replacement for the previous scheduled runs to ensure that no dependency update breaks MSS. Merging that PR is a manual step that can be done just as with any other PR and would then update the environment on the given target branch. This is essentially what was previously the (manual) trigger of a docker image creation.

Including new dependencies can be done with `pixi add`, which will also automatically add the dependency to the (pre-existing) lockfile. This means dependency additions can be part of the PR that necessitate them and they won't affect the entire environment (as they previously did, where they would trigger a full image rebuild) but instead just add that new package to the existing specification.

---

This (mostly) implements the ideas I've outlined in #2160. I wanted to substantiate what I had in mind, because I think there was some confusion there about what these ideas would entail.

I consider this to be a massive simplification of the CI setup, while retaining all required functionality (or even improving it). The additions count looks large due to the pixi.lock file, but that file is automatically generated. Outside of it this is a net negative in code size.

There is the minor issue that PRs created from GitHub Actions do not trigger workflow runs (an arbitrary and annoying limitation of GitHub Actions, if you ask me), so the checks in the lockfile update PR that I mentioned above wouldn't actually be created (yet). There are multiple workarounds available, the easiest being closing and re-opening the PR (and more are documented here: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs).

Of course, there would need to be documentation changes as well. This is a draft and I would like to discuss if this is a direction we want to go in before fleshing this out more.

@ReimarBauer @joernu76 just pinging you so you are aware of it, there is no sense of urgency with this.

2024-03-26 15:49 UTC, joernu76 commented
What the heck is pixi? This https://pixi.sh/latest/ ? Is this mature/stable? It doesn't have a wikipedia page and I have never heard from it...
So it is a backport of cargo for conda-forge??
I mean, frankly, *every* package manager is better than conda, so it must be better...
I assume this does only affect our development etc. and has no affect on our users?

2024-03-26 16:15 UTC, matrss commented
> What the heck is pixi? This https://pixi.sh/latest/ ? Is this mature/stable? It doesn't have a wikipedia page and I have never heard from it...

Yes, that link is correct. It is a relatively new package manager, it was released in summer last year (they had a release party at EuroSciPy 2023, Reimar and I attended it). It is developed by the same people that were/are behind mamba, so for what it's worth there is some credibility behind it.

> So it is a backport of cargo for conda-forge??

I haven't worked with cargo/rust in a while but yes, I think they took a lot of inspiration from that and there are many similarities in how they work.

> I mean, frankly, _every_ package manager is better than conda, so it must be better...

Hard agree.

> I assume this does only affect our development etc. and has no affect on our users?

Yes, the mss-feedstock and therefore the conda-forge package remains the same (and installable through conda, mamba, pixi or whatever else might work with conda-forge packages, with the usual caveat that conda-forge packages can not be tested and might break at any point in time due to the install-time dependency resolution - nothing new from this PR and a gripe I have with the entire conda packaging model).

2024-03-28 12:11 UTC, ReimarBauer commented
I recently gave a lighning talk at the Barcamp in Karlsruhe.

Sources:
https://prefix.dev/blog/pixi_a_fast_conda_alternative

There is also a talk by Wolf on pyconde in mid april

2024-03-28 12:28 UTC, ReimarBauer commented
with an uptodate conda you have same speed as with mamba, see 

https://conda.org/blog/2023-11-06-conda-23-10-0-release/

2024-04-02 11:36 UTC, matrss commented
> with an uptodate conda you have same speed as with mamba, see
> 
> https://conda.org/blog/2023-11-06-conda-23-10-0-release/

Speed isn't the issue that conda has, in my opinion. The issue is that it is impossible to define a development environment in its entirety right next to the source code (i.e. inside of a git repository). Mamba has the same issue, because its interface is basically the same as conda's. Cargo fixes this for the rust world with its Cargo.lock file pinning dependencies from crates.io, PDM or poetry (or others) can do the same for python on top of PyPI, nix can do it independently of the programming language using pinned references to nixpkgs, and pixi does it on top of the conda packaging ecosystem (also basically language independent). Conda or mamba simply don't provide this feature, speed is irrelevant in that case. (Also, using a lock file moves the dependency resolution to the step of creating the lock file, so that at install time there is no dependency resolution at all necessary. A no-op is strictly faster than any solver conda could possibly integrate.)

2024-05-25 12:51 UTC, ReimarBauer commented
With trying to differentiate the packages https://github.com/Open-MSS/MSS/pull/2390 I will likly get to a conda requirements.d/mswms.txt, requirements.d/mscolab.txt and likly a requirements.txt for the whole.

I am currently looking for the jinja syntax to read a requirements.txt files into the current meta.yaml which I prefer to use until we can migrate to e.g. rattler-build etc. on conda-forge too. The one in the feedstock is not identical because of the cross compilation. Without any extra hassle I want to be able to redo a build by cond build locally.

But keeiping that dir is then independent for switching in a first step to a requirements.txt instead of current transformation from a meta.yaml.  With the jinja2 Syntax there is then also no duplication.

2024-12-03 14:58 UTC, ReimarBauer reviewed
nice!
Wolf recently announced a speedup using conda-forge from prefix-dev.
https://x.com/wolfvollprecht/status/1863590394992193803

2024-12-03 15:38 UTC, ReimarBauer commented on pixi.toml
> +skyfield-data = ">=5"
>=6

when it not always uses the newest, we would need to enumber it each year

2024-12-03 15:39 UTC, ReimarBauer commented on pixi.toml
> +boa = "*"
we should remove this. 

This was also only an intermediate on the way to rattler-build

2024-12-03 15:40 UTC, ReimarBauer commented on pixi.toml
> +
this sections are a nice feature, so we could also add a section for the tutorials.

2024-12-03 15:44 UTC, ReimarBauer commented on pixi.toml
> +xmlschema = "<2.5.0"
the xmlschema and its pinning was removed some time ago
https://github.com/Open-MSS/MSS/pull/2117/files

2024-12-03 15:50 UTC, ReimarBauer commented on pixi.toml
> +menuinst = "*"
menuinst is not implemented for pixi, https://github.com/prefix-dev/pixi/discussions/1894

2024-12-03 16:02 UTC, matrss commented
@ReimarBauer this is still WIP, I have only rebased so far and didn't yet update the pixi.toml file to reflect all of the changes since end of March or work on the documentation or anything. I am also looking into `pixi upgrade` instead of specifying `=*` version constraints; that option has been newly added since I started this PR.

2024-12-03 16:17 UTC, ReimarBauer commented
> @ReimarBauer this is still WIP, I have only rebased so far and didn't yet update the pixi.toml file to reflect all of the changes since end of March or work on the documentation or anything. I am also looking into `pixi upgrade` instead of specifying `=*` version constraints; that option has been newly added since I started this PR.

I know that it has WIP state, but I like it especially because of the recent problems which perfectly illustrate what disadvantages we have if we don't do it. These are benevolent comments ;)

2025-02-11 16:59 UTC, matrss commented on .github/workflows/update-pixi-lockfile.yml
> +          token: ${{ secrets.PAT }}
This is assuming that the currently-configured PAT has the right permissions to create a PR against this repository.

2025-02-11 17:02 UTC, matrss commented on setup.py
> +    name="mslib",
This name change was necessary because of the name collision with the mss package on PyPI, which we also depend on. Otherwise the editable install of this MSS into the pixi environment was impossible.

2025-02-18 13:15 UTC, ReimarBauer commented on setup.py
> +    name="mslib",
I am not clear about the consequences. Does this mean that we would have to call ourselves MSLIB on conda-forge and within the project? I would then need to initiate a migration; it also has implications for publications.

If it all comes down to a renaming everywhere, then open-mss fits well with gh and open-mss.org.

The other mss project is called python-mss on conda-forge. If we choose a new name, we should do so carefully because "Mission Support System" is a very generic term.

D.h. am nächsten vom mapping her, wäre da open-mss.

2025-02-18 13:17 UTC, ReimarBauer commented on .github/workflows/update-pixi-lockfile.yml
> +          token: ${{ secrets.PAT }}
ok, I updated it on some places, end of year, we will see.

2025-02-18 13:38 UTC, ReimarBauer commented on .github/workflows/update-pixi-lockfile.yml
> +    runs-on: ubuntu-latest
there maybe a chiseled or slim package available which we can also use, but its not important, only if that takes time

2025-02-18 14:02 UTC, ReimarBauer commented on pixi.lock
> +      - conda: https://conda.anaconda.org/conda-forge/noarch/pytest-cov-6.0.0-pyhd8ed1ab_1.conda
does this mean we have all testing, devoloping tools always installed on a developer and users system?

2025-02-18 14:03 UTC, ReimarBauer commented on pixi.toml
> +numpy = "<2"
after merge on develop it is >2

2025-02-18 14:05 UTC, ReimarBauer commented on pixi.toml
> +
we maybe need dbus-python also on osx-64. I have this on my mss-9.3.1 installation env.

2025-02-18 14:10 UTC, ReimarBauer reviewed
I added some ideas/questions.

2025-02-18 15:10 UTC, matrss commented on setup.py
> +    name="mslib",
This is only the name of the python package defined by this setup.py file. It does not mean that we have to change the package name anywhere else AFAIU. PyPI should be the only package registry that actually enforces matching package names in the python package and the project on the index, if it even does that.

I've called it mslib because that is the name of the main module inside, but I agree it isn't a nice name. open-mss would sound good to me. `python-mss` is called that on conda-forge because all pure-python packages should get a `python-` prefix there AFAIK.

2025-02-18 15:16 UTC, matrss commented on .github/workflows/update-pixi-lockfile.yml
> +    runs-on: ubuntu-latest
I think you are confusing this with docker images? These are GitHub actions runner labels and all of the available ones (excluding the possibility of self-hosted runners) are listed here: https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories

2025-02-18 15:19 UTC, matrss commented on pixi.lock
> +      - conda: https://conda.anaconda.org/conda-forge/noarch/pytest-cov-6.0.0-pyhd8ed1ab_1.conda
Not really. `pixi {install,shell,run,...}` should only actually download the packages for the default environment, if you don't request the dev environment. Likewise for the other ones (addons, tutorials). The lock file only contains the combined environment resolution result.

Users aren't affected anyway since they do not interact with this pixi project at all.

2025-02-18 15:20 UTC, matrss commented on pixi.toml
> +numpy = "<2"
`>=2`

2025-02-18 15:30 UTC, matrss commented on pixi.toml
> +
I somehow remembered that the dbus-python package did not exist for osx at all, but it looks like it does. Weird.

2025-02-18 18:29 UTC, ReimarBauer commented on setup.py
> +    name="mslib",
let us change that name already to open-mss. Then we have used that already there and at some point someone again tries to create a pypi package it needs not another renaming.

We can change the inner later anyway.

2025-02-18 18:31 UTC, ReimarBauer commented on .github/workflows/update-pixi-lockfile.yml
> +    runs-on: ubuntu-latest
yes, catched

2025-02-18 19:34 UTC, ReimarBauer commented on docs/development.rst
>  Setup MSWMS server
Please also change in the MSWMS and MSColab sections also the calls.
I wanted to send a patch but somehow I do something wrong, "There was an error committing your changes: File could not be edited" 
Next time we meet I need to become "aufschlaut"

https://iffmd.fz-juelich.de/IENAfBSeRhuFDO5VIN2s3Q#
Then we have all relevant here updated

2025-02-18 19:45 UTC, ReimarBauer requested changes
I tried the whole process on my Mac also for the servers not only the ui.
a few commands should be changed in the development.rst for the servers

https://iffmd.fz-juelich.de/IENAfBSeRhuFDO5VIN2s3Q#

we should use open-mss from now on in the setup.py.

2025-02-19 13:26 UTC, matrss commented on docs/development.rst
>  Setup MSWMS server
The error doesn't read like anything I've ever encountered from git. At which point did you get it?

Anyway, I've made those changes.

2025-02-19 13:28 UTC, matrss commented
Off-topic: I like the new grouping of the CI results, makes it much easier to see what failed at a glance...

2025-02-19 13:32 UTC, matrss commented on setup.py
> +    name="mslib",
I changed it. We should reserve the open-mss name on PyPI though, so we don't run into this again in the future.

2025-02-19 17:18 UTC, ReimarBauer commented on docs/development.rst
>  Setup MSWMS server
I´d not tried again today, this was the path


https://github.com/user-attachments/assets/a66b4c7f-3965-4fbc-ae28-5b585afd97c5

2025-02-19 17:23 UTC, ReimarBauer commented on setup.py
> +    name="mslib",
yes, I do

2025-02-19 17:26 UTC, ReimarBauer approved these changes
Great !
Thx

2025-02-19 19:28 UTC, ReimarBauer commented on setup.py
> +    name="mslib",
https://test.pypi.org/project/open-mss/

just learned a global installed pixi has precedence

```
(venv) (base) reimarbauer@MacBook-Pro-von-Reimar venv % bin/mss
open-mss is a conda-forge package.You can install it with pixi.
Get pixi from https://pixi.sh/latest/ for your operation system.

pixi global install mss

Usage:
    msui -h
    mswms -h
    mscolab -h

```
[our pypi project
](https://github.com/Open-MSS/open-mss)

2025-02-21 10:52 UTC, joernu76 approved these changes

2025-02-21 10:53 UTC, joernu76 commented
I have several technical questions, which we may adress in todays meeting. Generally this seems like a step in a good direction!

2025-02-21 14:07 UTC, merged