fixed DeprecationWarning in requests use in auth.py
Open-MSS/MSS pull request #2570
Opened 2024-10-19 11:46 UTC by YogeshRathee512

Purpose of PR?:

Fixes #1787
Resolves the DeprecationWarning for non-string passwords in requests when using keyring.

Does this PR introduce a breaking change?
No, it ensures future compatibility with requests 3.0.0 by handling password strings correctly.

If the changes in this PR are manually verified, list down the scenarios covered::

Verified that credentials are correctly retrieved from keyring.
Checked that the system no longer triggers the DeprecationWarning.
Tested login flow for HTTP authentication using the stored credentials.
Ensured that errors are handled properly when keyring is unavailable or credentials do not exist.
Additional information for reviewer?:
This PR is part of a follow-up on improving error handling and avoiding deprecated practices with third-party libraries such as requests. It is a continuation of previous work on authentication refactoring.

Does this PR result in some Documentation changes?
No.

Code Changes:
Initial Code:
<img width="505" alt="image" src="https://github.com/user-attachments/assets/bd98fdbc-9cc8-4db8-83f2-38fbbbdf55b8">

<img width="464" alt="image" src="https://github.com/user-attachments/assets/b68dcf60-6267-4de2-ac01-70bf6decb9c0">

Updated Code:
<img width="405" alt="image" src="https://github.com/user-attachments/assets/f18ace91-e8de-4c09-ad73-26fd85c841a7">

<img width="385" alt="image" src="https://github.com/user-attachments/assets/05a487b3-ac9e-4fef-83c7-da768759d1a2">

Checklist:

 Bug fix. Fixes #1787
 New feature (Non-API breaking changes that add functionality)
 PR Title follows the convention of <type>: <subject>
 Commit has unit tests

2024-10-19 12:51 UTC, ReimarBauer commented on mslib/utils/auth.py
> +                if password is None:
We don't want to save empty passwords to the keyring

2024-10-19 12:52 UTC, ReimarBauer reviewed
How is the change related to the requests module? Can you provide a test which shows what you want to fix?

2024-10-19 13:00 UTC, ReimarBauer commented on mslib/utils/auth.py
> +    handles passwords from the keyring for login and http_auth
good, our spellchecker had not found that :)

2024-10-19 13:03 UTC, ReimarBauer commented on mslib/utils/auth.py
> +                if password is None:
We don't allow to save empty strings as password, that is not a good idea, to remove None here.

2024-10-19 13:26 UTC, ReimarBauer commented on mslib/utils/auth.py
> +    auth = constants.AUTH_LOGIN_CACHE.get(server_url, (name, ""))
We don't accept empty passwords. And should not start using them in the AUTH_LOGIN_CACHE.

2024-10-19 13:27 UTC, ReimarBauer commented
When we have an example how we submit None over requests, then we should catch that where we did that.

2024-10-19 13:34 UTC, ReimarBauer requested changes
see comments

2024-10-19 18:54 UTC, YogeshRathee512 commented
Respected ReimarBauer , I saw your message late at night and wanted to keep you updated. As I’m still a beginner with open source, I’ll need a bit more time to review the code and understand my mistakes. I’ll be working on it tomorrow and will reach out as soon as possible with any new solutions or updates.

2024-10-20 07:03 UTC, ReimarBauer commented
Welcome @YogeshRathee512 

there are two options currently where we use the current functionality. 
 - https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/mscolab.py#L64
This is not yet merged to develop. 
 - https://github.com/Open-MSS/MSS/blob/GSOC2024-rebased-autoplot/mslib/utils/mssautoplot.py#L49

see if it is necessary to intercept the sending of None here. You can look at it via debugging, or via a test.

2025-02-24 10:32 UTC, ReimarBauer commented
the proposed PR does not take care, where we could send None. The issue meanwhile was closed.

2025-04-02 17:15 UTC, closed without merging