fix: LinearView and SideView plot to display operation name
Open-MSS/MSS pull request #2592
Opened 2024-12-22 18:30 UTC by TheMightyRaider

**Purpose of PR?**:
To show operation name in the sideview and linearview plot area.

Fixes #2461 

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:
 - Tested using the dummy data, which was created as mentioned in the [docs](https://open-mss.github.io/develop/Setup-Instructions).

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_
- There is design change in the graphs, The sideview and linearview plot graphs would contain _operation name_ at the top-centre of the plot as shown in the images below,
<img width="1043" alt="Screenshot 2024-12-22 at 11 28 35 PM" src="https://github.com/user-attachments/assets/81f7fc78-ce82-4093-a893-775334a7d827" />
<img width="912" alt="Screenshot 2024-12-22 at 11 39 19 PM" src="https://github.com/user-attachments/assets/d0b56147-4d8e-4409-84d6-681bcb3a9613" />

**Does this PR results in some Documentation changes?**
_If yes, include the list of Documentation changes_
- The tutorial [video](https://mss.readthedocs.io/en/stable/tutorials/tutorial_msui_views.html) might need to be reuploaded

**Checklist:**
- [X] Bug fix. Fixes #2461 
- [X] New feature (Non-API breaking changes that adds functionality)
- [X] PR Title follows the convention of  `<type>: <subject>`
- [ ] Commit has unit tests

2024-12-27 08:25 UTC, ReimarBauer commented
Hi @TheMightyRaider this is partly done. it is a good step. We can have opened views while we can change the flight or operation. 
You can try with a test database setup of mscolab or create a second Flight track.

```
MSS$ python mslib/mscolab/mscolab.py db --seed
MSS$ python mslib/mscolab/mscolab.py start
```
look into the seed module for credetentials

When we change the model we need also to update this entry on the plot. This is missing yet in the solution.

![changeactivemodel](https://github.com/user-attachments/assets/f181969b-4cd9-47be-9b7e-26b4721f14a3)

2024-12-27 08:34 UTC, ReimarBauer commented
When showing some of the data from a demo server, the position of the name is overlapped by the other text

![image](https://github.com/user-attachments/assets/5f216a38-7dd0-4e0a-8c9a-93aa6d2b0ecd)

Maybe place it right of the plot helps.

2024-12-27 14:23 UTC, TheMightyRaider commented
Thank you @ReimarBauer for your feedback, Will fix the issues mentioned!

2024-12-27 22:07 UTC, TheMightyRaider commented
@ReimarBauer , Pushed a commit with the review changes you had mentioned! Let me know if it looks good on your end!

2024-12-30 11:02 UTC, ReimarBauer requested changes
I don't see the information on a linearview 

![image](https://github.com/user-attachments/assets/c18ca900-17c5-473f-851f-ad9b3c9c7249)

on topview please remove the old one  (model name) on the left lower corner. There we have it now twice.

![image](https://github.com/user-attachments/assets/0406f16b-75e1-4175-b879-f345c4f5742c)

2024-12-30 16:33 UTC, TheMightyRaider commented
Sorry about that @ReimarBauer , Thanks for your feedback once again.
- I have pushed a fix for the "repetition of title in topView" issue.
- Regarding "The title not been shown in the LinearView" issue, It does show in my end. Can you guide how to reproduce your graph?


https://github.com/user-attachments/assets/0e34ec76-8961-47c2-9f97-b2aee5d7fa5b

2024-12-30 17:13 UTC, ReimarBauer commented
On the place where EPSG was printed there where also optional airdata credentionals on topview shown. The place was for EPSG and that good. Or how does this look now when you select that in the docking widget?

2024-12-30 17:19 UTC, ReimarBauer commented
On the place where EPSG was printed there where also optional airdata credentionals on topview shown. The place was for EPSG and that good. Or how does this look now when you select that in the docking widget?


Click Server/Layer and add a Server url. E.g. http://open-mss.org (not https)

Then select a layer. The model name should be on the plot too.

2024-12-30 18:01 UTC, TheMightyRaider commented
@ReimarBauer  When the size of the window is small, The text gets crowded.
<img width="960" alt="Screenshot 2024-12-30 at 11 12 58 PM" src="https://github.com/user-attachments/assets/710c6c05-31ad-4164-9f2c-8ea34653f9b4" />
<img width="1388" alt="Screenshot 2024-12-30 at 11 13 04 PM" src="https://github.com/user-attachments/assets/ec00c591-7906-4edc-9d49-ef19062cb55f" />

2024-12-30 18:05 UTC, ReimarBauer commented
> @ReimarBauer  When the size of the window is small, The text gets crowded.
> <img width="960" alt="Screenshot 2024-12-30 at 11 12 58 PM" src="https://github.com/user-attachments/assets/710c6c05-31ad-4164-9f2c-8ea34653f9b4" />
> <img width="1388" alt="Screenshot 2024-12-30 at 11 13 04 PM" src="https://github.com/user-attachments/assets/ec00c591-7906-4edc-9d49-ef19062cb55f" />
> 

The name is mostly needed on a saved plot / printed plot.

On screen having it at the window  title is ok.

2024-12-30 19:33 UTC, TheMightyRaider commented
I tried putting the title in the bottom left. But now it does overlap with the x-axis values during sideview plot. 
I feel the plot isn't scaling well when the screen of the window is shrieked, Even the values of the y-axis for the sideview plot are semi hidden by default. @ReimarBauer

2025-01-02 11:39 UTC, ReimarBauer commented
I think we should keep on topview the location where we have EPSG for everything besides the model.name

With airdata there can be more text added there and we don't have this and EPSG for the other views

without your change:

![image](https://github.com/user-attachments/assets/6b43c178-0117-4a47-b051-d8d13e6e50eb)

2025-01-02 11:46 UTC, ReimarBauer commented
On the linearview with data the model.name is gone

![selection_update](https://github.com/user-attachments/assets/f30aecd8-bd7c-424a-90b7-5150556fe0e8)

2025-01-02 12:23 UTC, ReimarBauer commented
ideas are welcome to improve matplotlib/qt visualizations.

2025-01-06 18:42 UTC, TheMightyRaider commented
> I think we should keep on topview the location where we have EPSG for everything besides the model.name
> 
> With airdata there can be more text added there and we don't have this and EPSG for the other views
> 
> without your change:
> 
> ![image](https://private-user-images.githubusercontent.com/278728/399689802-6b43c178-0117-4a47-b051-d8d13e6e50eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxODg1ODEsIm5iZiI6MTczNjE4ODI4MSwicGF0aCI6Ii8yNzg3MjgvMzk5Njg5ODAyLTZiNDNjMTc4LTAxMTctNGE0Ny1iMDUxLWQ4ZDEzZTZlNTBlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQxODMxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmE0MTE4Y2FhNDA3YzRmN2IwYWI2YWY2OTcxOTE3N2NkZmE4MzFkNjA0MDhiZDM0N2NiZTgzMjU2YWUxZGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ui89KcysbgAo17qcPb6emMZ9ZXfAKssTtoHv7LQeRjs)

@ReimarBauer, I'm not sure whether I got right. Do you mean to say, we keep the model name alone at the top right for all the three views [ side, top and linear ] ?

2025-01-07 10:30 UTC, ReimarBauer commented
@TheMightyRaider yes we should have same place for the model name on all three views. Currently at the top right is the best option. The special information EPSG, etc on TopView should be kept on its origin place.

2025-01-07 18:04 UTC, TheMightyRaider commented
@ReimarBauer, Pushed the changes!

2025-01-08 15:18 UTC, ReimarBauer commented
On github is a rule for the CI it did not start for new contributors automatically. I cannot change that.
But you can look locally too. 

The tests can ran locally, e.g. https://github.com/Open-MSS/MSS/blob/develop/.github/workflows/testing.yml#L68, https://github.com/Open-MSS/MSS/blob/develop/.github/workflows/lint.yml#L69

2025-01-08 15:19 UTC, ReimarBauer commented
@TheMightyRaider look on the flake8 linter, meanwhile I play with the changes

2025-01-08 15:41 UTC, TheMightyRaider commented
@ReimarBauer , Fixed the linting issues thrown by flake8.

2025-01-09 08:08 UTC, ReimarBauer requested changes
ok, fine

there needs a last refactoring change done. When I look with PyCharm (I guess other have also such options) I see the name parameter is not used anymore and we should change the API and content of  update_info_text too.

![image](https://github.com/user-attachments/assets/b7177f7d-0bcf-4824-b519-4a4dadd219c2)

2025-01-10 14:37 UTC, ReimarBauer commented
@TheMightyRaider have you seen the opportunity to refactor the sigature of update_info_text ?

2025-01-10 16:28 UTC, TheMightyRaider commented
@ReimarBauer , Nice find! I have updated the `update_info_text` function. Sorry about the delay.

Quoting below your earlier comment,

> ok, fine
> 
> there needs a last refactoring change done. When I look with PyCharm (I guess other have also such options) I see the name parameter is not used anymore and we should change the API and content of update_info_text too.

I don't understand what you meant by API here?

2025-01-10 16:41 UTC, ReimarBauer commented
> I don't understand what you meant by API here?

We have not defined a public application programming interface. That means any signature change is also an API change. 
In that case the function has now less parameters than before.

2025-01-10 17:06 UTC, TheMightyRaider commented
Ahh okay! Thanks for the clarification!

2025-01-10 17:48 UTC, TheMightyRaider commented
https://github.com/Open-MSS/MSS/blob/develop/.github/workflows/testing-all-oses.yml, This workflow is failing. 😢

2025-01-10 18:06 UTC, ReimarBauer commented
If it is because of timeout or mac tests that is not related to your changes.

2025-01-13 07:28 UTC, ReimarBauer approved these changes
Thx, for solving this

2025-01-13 07:30 UTC, merged

2025-01-13 10:13 UTC, TheMightyRaider commented
Thank you for your guidance! @ReimarBauer