Create CODE_OF_CONDUCT.md
Open-MSS/MSS pull request #646
Opened 2021-01-26 18:28 UTC by BobinMathew

2021-01-27 09:32 UTC, ReimarBauer reviewed
looking at the source, seen there is a v2.0 
https://www.contributor-covenant.org/version/1/4/code-of-conduct.html

please use the v2.0

2021-01-27 09:34 UTC, ReimarBauer commented on CODE_OF_CONDUCT.md
> +# Contributor Covenant Code of Conduct
this line needs a change, 

Contributor Mission Support System Code of Conduct

2021-01-27 17:03 UTC, joernu76 commented
Personally I see the need to formalize these kind of things only after the need arises.
But the document seems pretty standard and seems reasonable.

2021-01-27 17:04 UTC, joernu76 approved these changes, later dismissed

2021-01-27 17:18 UTC, BobinMathew commented
what about the Pytest MSS/Test-MSS error?

2021-01-27 17:22 UTC, joernu76 commented
> what about the Pytest MSS/Test-MSS error?

We are currently setting everything up. The develop+stable branches must be fixed first, which should be completed tomorrow. Then further pull requests can be merged.

2021-01-27 18:53 UTC, ReimarBauer requested changes
The latest version is https://www.contributor-covenant.org/version/2/0/code_of_conduct/
`We as members, contributors, and leaders pledge to make participation in our community a harassment-free experience for everyone, ....
`
Seems they have the kind of member states further developed and also described the enforcement guidelines and some more changes.


What are the reasons to use 1.4 and not 2.0?

2021-01-28 08:14 UTC, joernu76 commented
I agree that the V2.0 is better suited.

2021-01-28 09:02 UTC, BobinMathew commented
Yes this https://www.contributor-covenant.org/version/2/0/code_of_conduct/ seems better

2021-02-01 10:12 UTC, joernu76 requested changes
Update to 2.0 required.

2021-02-01 11:21 UTC, joernu76 approved these changes

2021-02-01 16:54 UTC, ReimarBauer requested changes
Please add the names of the leader , see line 35

[INSERT CONTACT METHOD]

2021-02-01 16:54 UTC, ReimarBauer commented on CODE_OF_CONDUCT.md
> +
we should add the email of Joern and Reimar. 

similar to

Enforcement of https://opensource.org/codeofconduct

2021-02-01 16:54 UTC, ReimarBauer commented on CODE_OF_CONDUCT.md
> +
- rb.proj@gmail.com
- j.ungermann@fz-juelich.de

2021-02-24 19:03 UTC, ReimarBauer commented on CODE_OF_CONDUCT.md
> +
this little bit I add afterwards

2021-02-24 19:04 UTC, ReimarBauer approved these changes

2021-02-24 19:54 UTC, merged