.format replaced with f ""
Open-MSS/MSS pull request #671
Opened 2021-02-08 21:15 UTC by SergeLeon

.format replaced with f "" wherever possible, except for tests

2021-02-18 11:14 UTC, ReimarBauer requested changes
please solve this merge conflict

2021-02-19 10:30 UTC, Marilyth submitted a review, later dismissed

2021-02-19 10:30 UTC, Marilyth commented on mslib/msui/wms_control.py
> +                     .replace("?request=GetCapabilities",
Something seems very awry here

2021-02-19 14:52 UTC, SergeLeon commented on mslib/msui/wms_control.py
> +                     .replace("?request=GetCapabilities",
I solved all the problems of the merge

2021-02-23 11:50 UTC, ReimarBauer reviewed
What changed on that file ? mslib/mswms/xml_templates/get_capabilities130.pt

2021-02-23 11:56 UTC, ReimarBauer approved these changes, later dismissed

2021-02-23 12:22 UTC, ReimarBauer requested changes
That is allmost done. There are two files too much in this pull request

service_exception130.pt and service_exception130.pt seems to have changes in the amout of whitespace. 

We need to take care for the issue content and the work done in the PR.
This PR is finished when the service_exception130.pt and service_exception130.pt  are changed to origin state.

Later on a release we can lookup all closed issues related to the released version. If there are other changes done that is not easily to keep track.

2021-02-23 12:29 UTC, ReimarBauer commented
@SergeLeon let me know if you want to join our slack channel. 
https://open-mss.github.io/develop/GSOC2021/ideas

2021-02-24 19:56 UTC, ReimarBauer commented
> That is allmost done. There are two files too much in this pull request
> 
> service_exception130.pt and service_exception130.pt seems to have changes in the amout of whitespace.
> 
> We need to take care for the issue content and the work done in the PR.
> This PR is finished when the service_exception130.pt and service_exception130.pt are changed to origin state.
> 
> Later on a release we can lookup all closed issues related to the released version. If there are other changes done that is not easily to keep track.


OK, good work over all :)

2021-02-24 19:56 UTC, ReimarBauer approved these changes

2021-02-24 20:15 UTC, merged