Resolves Issue #650
Open-MSS/MSS pull request #687
Opened 2021-02-24 08:30 UTC by nakul-shahdadpuri

@Tanish0019 @ReimarBauer 
Removed Email field from admin window in mscolab.
## Screenshot of the current look
![Screenshot from 2021-02-24 13-54-52](https://user-images.githubusercontent.com/43999912/108971730-9d441480-76a8-11eb-910c-7734c9afa925.png)

2021-02-24 08:36 UTC, ReimarBauer requested changes
comments can be used for commenting something, removing lines should be removing them ;)

2021-02-24 08:44 UTC, Tanish0019 commented
@nakul-shahdadpuri I see you're populating table by removing emails from the response sent back in the frontend. It will be better if you instead update the mscolab api for this and not do the filtering on the frontend. Also can you play around with the window/table sizes in the UI so that username column is not so stretched. It looks a bit weird right now. Thanks!

2021-02-24 08:48 UTC, Tanish0019 commented
Also we never change the ui files by hand. Always use the Qt designer to update the .ui files. [This](https://realpython.com/qt-designer-python/) is a helpful article on getting started with qt designer

2021-02-24 09:00 UTC, ReimarBauer commented on mslib/msui/mscolab_admin_window.py
> +        print(users)
this will users confuse. Instead you can use logging.debug

2021-02-24 09:01 UTC, ReimarBauer commented on mslib/msui/qt5/ui_mscolab_admin_window.py
> +        # item = QtWidgets.QTableWidgetItem()
if this is not done in the ui file by the designer it will return by pyuic

2021-02-24 09:02 UTC, nakul-shahdadpuri commented
@ReimarBauer yup I'll do that. 
@Tanish0019 I initially had started by changing the [models.py](https://github.com/Open-MSS/MSS/blob/develop/mslib/mscolab/models.py) file, but I wasn't sure if the API was being called anywhere else, so I just removed it from the admin window frontend. I'll try tinkering with the models now. Yup, the UI looked a little stretched I'll work on that too. :)

2021-02-24 09:04 UTC, Tanish0019 commented
@nakul-shahdadpuri no need to update models.py that defines the schema. We need to update 2 apis which are used to populate these two tables. You can just remove email from the response in those apis 😀

2021-02-27 09:50 UTC, nakul-shahdadpuri commented
@Tanish0019 @ReimarBauer 
This is how the admin tab looks now. I removed the emailid attribute from the response by changing the API. 
![Screenshot from 2021-02-27 15-14-42](https://user-images.githubusercontent.com/43999912/109383820-104ec480-790f-11eb-9bff-fa705bcc5ba4.jpg)

2021-03-03 06:20 UTC, ReimarBauer requested changes
You have to use designer ui_mscolab_admin_window.ui to remove elements there and convert it by pyuic5 to  ui_mscolab_admin_window.py

The ui_mscolab_admin_window.py is never edited manually.

https://pythonbasics.org/qt-designer-python/

2021-03-05 05:42 UTC, ReimarBauer requested changes
look at pytest -k test_mscolab_admin_window.py
The tests needs a change too.

take care on test output on github. (of course tests should fit)

I tried a clone of your repositiory, it looks to me like in this peek video. On the right side the permission is not shown.

![admin_window](https://user-images.githubusercontent.com/278728/110073986-b3c12e80-7d80-11eb-95fc-1552f1675934.gif)

2021-03-06 14:12 UTC, ReimarBauer commented
I can't reproduce the proposed solution. 
![permissions_missing](https://user-images.githubusercontent.com/278728/110209754-6cc15f00-7e8e-11eb-9903-f8927bbe4f86.png)

2021-03-06 14:43 UTC, ReimarBauer commented
@Tanish0019 or/and @Marilyth please can you try out the proposed solution. Perhaps my setup can have issues

2021-03-06 17:53 UTC, nakul-shahdadpuri commented
@ReimarBauer @Tanish0019 @Marilyth 
I am still getting the following output.
I had removed the email field from [file_manger.py](https://github.com/Open-MSS/MSS/blob/develop/mslib/mscolab/file_manager.py) in fetch_users_with_permission and fetch_users_without_permission which was being called in [server.py](https://github.com/Open-MSS/MSS/blob/54a0439b47ab0ae164122e6d6a35a59dc313ddbf/mslib/mscolab/server.py#L405)
I am not sure why the email field is still present in your version.
![current look](https://user-images.githubusercontent.com/43999912/110215892-242b9500-7ed2-11eb-8a3a-d583bf51e03e.jpg)

2021-03-06 21:04 UTC, ReimarBauer commented
I get a new clone tom. and try again.

2021-03-07 09:16 UTC, ReimarBauer commented
I'm not sure if you are on our slack channel. If you want an invite send me a mail to mss-info@fz-juelich.de If you are there ping me. (https://open-mss.github.io/contributing/)

We should find what makes this difference. I tried to debug the behaviour with the yourmss server.

My server sends as second attribute the email address.

![mssdata](https://user-images.githubusercontent.com/278728/110234700-376b4e80-7f2c-11eb-94cb-19425bb6af47.png)

![users](https://user-images.githubusercontent.com/278728/110234880-4bfc1680-7f2d-11eb-9e6c-ca72f1f5007f.png)

2021-03-07 09:48 UTC, ReimarBauer commented
Got it. My failure. yourmss is on the 2.0.1 server version ;)

2021-03-07 09:49 UTC, ReimarBauer approved these changes

2021-03-07 09:52 UTC, merged