Reworked add project dialogue to properly show file name.
Open-MSS/MSS pull request #735
Opened 2021-03-24 13:50 UTC by joernu76

Fix issue #734

2021-03-24 20:34 UTC, ReimarBauer commented on mslib/msui/qt5/ui_add_project_dialog.py
> +# Created by: PyQt5 UI code generator 5.12.3
this is also the version of qt we currently can't have on a fresh installation on linux, I check this tom. with the old version. Anyway after we changed the channel order we will all have 5.12.9

2021-03-24 21:32 UTC, ReimarBauer requested changes
![old_new](https://user-images.githubusercontent.com/278728/112385863-6a655e80-8cf0-11eb-986b-c4acd46ffd5b.png)

on the left site is the old on the right the new one.
I agree to the explaination text, but it looks like an input field because of the white color. 
Can it become a label or a changed background?

just for description,  uploading a file is not mandatory, it will overwrite the provided server code.

2021-03-25 08:12 UTC, joernu76 commented
Mmh. The "label" had the problem that it is invisible and has no frame  or similar. I can try to "disable" the element, which might to the visual tricks. 
Any suggestions to a widget showing a text that is *not* editable? @Marilyth

2021-03-25 12:32 UTC, joernu76 commented
I "disabled" the dialogue such that it is now grey.
We can certainly redesign the flow, but that is out-of-scope for my fix.

2021-03-25 13:19 UTC, ReimarBauer approved these changes
Thx

2021-03-25 13:21 UTC, merged