improved installation guide, fixes #856
Open-MSS/MSS pull request #860
Opened 2021-04-29 12:04 UTC by ReimarBauer

2021-04-29 12:14 UTC, joernu76 submitted a review, later dismissed

2021-04-29 13:09 UTC, jgrooss requested changes
installation.rst, please change line 30 to
"The fastest way to get..."

2021-04-30 05:38 UTC, Marilyth approved these changes

2021-04-30 08:15 UTC, jgrooss approved these changes

2021-04-30 08:18 UTC, merged