improved the workflow, only on merge
Open-MSS/MSS pull request #964
Opened 2021-05-17 20:01 UTC by ReimarBauer

2021-05-18 08:21 UTC, Marilyth commented
It is hard to verify if this works as expected or not.
Have you done any test runs?

2021-05-18 09:15 UTC, ReimarBauer commented
I have forked the example
https://github.com/ReimarBauer/github-actions-pr-close-showcase/actions
the configuration example for coveralls is from
https://github.com/conda-forge/conda-smithy/blob/master/.github/workflows/tests.yml

2021-05-18 10:45 UTC, Marilyth commented
I will play around with this a bit. Sadly testing out actions, especially ones as complex as on merged PRs is taking time.

2021-05-18 11:47 UTC, ReimarBauer commented
> I will play around with this a bit. Sadly testing out actions, especially ones as complex as on merged PRs is taking time.

Thx. If that works probably can extend this too. I can manually create updates until we have this productive.

2021-05-18 17:45 UTC, Marilyth requested changes
Generally I think it would be easier to accommodate this into our default test action, as a test need to be performed anyway.
https://github.com/Marilyth/MSS/commit/d7b5dddce9ae0a708d1f7ee3d60115302558f900

2021-05-18 17:45 UTC, Marilyth commented on .github/workflows/coveralls.yml
> +        coveralls --service=github mslib
If I am not mistaken, coveralls by itself does nothing but to upload a precreated coverage report, e.g. by pytest-cov.
As it stands here, coveralls will just upload an empty report with 0% coverage.

Also `mslib` must be removed from the `coveralls --service=github mslib` command as that is invalid syntax

2021-05-18 17:45 UTC, Marilyth commented on .github/workflows/coveralls.yml
> +    types: [ closed ]
This seems very specific.
Why not create a coverage on every push, as opposed to every merged pull request?
It would make the rest of the action simpler.

2021-05-19 11:56 UTC, ReimarBauer commented on .github/workflows/coveralls.yml
> +    types: [ closed ]
I agree :)
We know then also when a lot new code without tests gets added.

2021-05-19 14:25 UTC, ReimarBauer commented
will be differently implemented

2021-05-19 14:25 UTC, closed without merging