Adds an MSS updater
Open-MSS/MSS pull request #984
Opened 2021-05-21 13:50 UTC by Marilyth

fixes #899 
1. Check if __version__ is a lower number than conda search mss
2. Create a "mss-tmp-env" environment and install the newest mss version within in
3. Make sure the right mss version was installed
4. Replace the current environment with the tmp environment

I am still unhappy with this solution, but it is the best I could find so far.
Also it seems [coverage does not capture QThreads](https://github.com/nedbat/coveragepy/issues/686), which is a bummer since the majority of the updater is running in the background.

2021-05-22 19:37 UTC, ReimarBauer commented
on windows we used 
```
mamba install mss python=3.9 
```
this was used by me recently also on linux.

probably we could verify first which python version is available and not request a minor one.

2021-05-25 15:02 UTC, Marilyth commented
Your command works only if there is no mss preinstalled I think. Otherwise mamba will keep the old mss version and be happy with it.
This worked for me on all my cases, be it a fresh environment or as a mss update
```
mamba install mss={version} python
```
where {version} is the latest one. Is there a reason to specify 3.9 instead of just telling mamba to match it to the newest mss @ReimarBauer ?
I have once managed to completely destroy my environment in which case that command didn't work. Which is why the environment replacement exists, but it is very dangerous if interrupted.

2021-05-29 10:06 UTC, ReimarBauer commented
> Your command works only if there is no mss preinstalled I think. Otherwise mamba will keep the old mss version and be happy with it.
> This worked for me on all my cases, be it a fresh environment or as a mss update
> 
> ```
> mamba install mss={version} python
> ```
> 
> where {version} is the latest one. Is there a reason to specify 3.9 instead of just telling mamba to match it to the newest mss @ReimarBauer ?
> I have once managed to completely destroy my environment in which case that command didn't work. Which is why the environment replacement exists, but it is very dangerous if interrupted.

The previous python=3.9 was some time ago a solution for a few windows installations.

2021-05-29 10:21 UTC, ReimarBauer commented
the replacement of an existing env is something which should be explained to the user. And I'm still not sure if we should do this automated. 

I'm also not sure if this scales, when a user has own plugins, libs additional installed in an mssenv. 

An other option is to guide the user through these steps for a backupped new installation. So it is half automated and we could also verify that it probably will be successful.

2021-05-31 14:47 UTC, Marilyth commented
> the replacement of an existing env is something which should be explained to the user. And I'm still not sure if we should do this automated.
> 
> I'm also not sure if this scales, when a user has own plugins, libs additional installed in an mssenv.
> 
> An other option is to guide the user through these steps for a backupped new installation. So it is half automated and we could also verify that it probably will be successful.

I fully agree. I pursued the ability to create and replace the environment in case an update does not work, but I had to give up.
It did work, sometimes, sometimes not. Random segfaults occured, crashes to the updater, permission issues on Windows. Ugh. This is not worth it.

2021-05-31 16:45 UTC, ReimarBauer requested changes
@Marilyth I do later a deeper review. I've seen already that it is centric to the UI user which is a good choice. 

I would also like to have a command line feature, at least for the servers. That must not do everything like the gui but it should log or output on a command option that the version is outdated. If that is too much now we can postpone that.

2021-05-31 16:45 UTC, ReimarBauer commented on mslib/msui/updater.py
> +    mslib.msui.multilayers
name conflicht

2021-05-31 19:00 UTC, Marilyth commented
Sure, I will detach the functions from the UI and bring the updater to the servers also.

2021-05-31 20:37 UTC, ReimarBauer commented
played a little with it, with some fake versions. Works pretty well :)
unfortunately have the current versions not that feature ;)

2021-06-01 19:51 UTC, ReimarBauer approved these changes
very well done

2021-06-01 19:51 UTC, merged